### ISSUE TITLE
[Feature Request] Dynamic view resizing based on length of feature 

### ISSUE THREAD

**Issue by fidibidi** [igvteam/igv#1019]
As always, thank you for your wonderful software!

Just a thought:
When ctrl-f'ing through bed file, having the option for IGV to resize itself to fit whole features inside of the view window would be incredibly time-saving for the type of analysis done at our company, and I'm sure others!

**Comment by malcook** [comment]
Perhaps the preference could be expressed as a fraction of the feature to display on either side of the centered feature, eg:  a value of 15% would cause a 1Kbp feature to display with 150bp flanking on either side.  

This would satisfy my previous #259

**Comment by fidibidi** [comment]
@jrobinso 

Think you might be able to point me in the right area of the codebase to fiddle around and see I can't come up with some implementation of it for a custom version of IGV? (I've done some tinkering with the codebase before!) 

Our lab's chief medical officer has been asking me to try and see if I can't get some sort of functionality like this implemented, as he is afraid he will accidentally miss something important during his IGV sessions.

**Comment by jrobinso** [comment]
@fidibidi You could start with GlobalKeyDispatcher where ctrl-f and ctrl-b get handled.    The method "nextFeature" does the "goto" and sets the start end range.    Since the size of the feature is also known in that method it should be pretty easy to make it resize to fit that feature.   It looks like it currently calls "centerOnLocation" if on the same chromosome, you would want to change that to "frame.jumpTo", as done just 2 lines above, and set the start (origin) and end accordingly.

So I think the main code to look at is lines 428 - 440 or so in GlobalKeyDispatcher.

These pointers are from just a few minutes looking at the code and could be off base, keep that in mind if it doesn't work.

If you are successful let me know,  I could possibly just copy your code and make this a user preference.

**Comment by fidibidi** [comment]
Thanks @jrobinso !!! This is exactly what I was looking for.

**Comment by malcook** [comment]
@fidibidi - did you possibly share your implementation upstream for possible inclusion into IGV?

**Comment by fidibidi** [comment]
Hey!
I believe this feature was added new versions of IGV!
Not sure if I ever tried to update the source code.

Jim’s gives great suggestions on how to do so tho!

**Comment by malcook** [comment]
Ah, yes, of course, you're right, I'd forgotten, "Preferences > General > Jump To Next Feature Options" indeed provides for this.
