### ISSUE TITLE
[Question] Improving performance when using URL loaded tracks. 

### ISSUE THREAD

**Issue by fidibidi** [igvteam/igv#1113]
Hello!

Just wanted to ask and see if anyone may have some suggestions for improving IGV performance when using URL loaded tracks. 

For context:
I'm working on a machine with 64gb ram, and a decent processor, I changed the igv_arguments file so that I'm allowing IGV to use up to 32GB of ram ( is there a cap here btw? )
I'm using some presigned S3 URLs, linking to .bam files that are quite large... around 50gb, as well as some other vcf files. 

IGV runs well for a little, but eventually, slows down, to the point where I have to reload the session, because the performance drops a bunch. 

Just wondering if there were any things I could try to keep the performance high! The alternative, which is to download all files locally, is a bit daunting....

As always, love IGV!
Thanks!

**Comment by jrobinso** [comment]
Its impossible to say what is causing this without the ability to reproduce the conditions here.   The size of the files are not relevant, assuming they are indexed.   When you say "eventually",  how long? 

Its possible that using too much memory could bog the process down as "garbage collection" could be deferred since there's plenty of memory,  then bog down when it finally kicks in due to the large amount of accumulated objects.   You might try starting with the default 8GB.   Was there a reason you needed 32GB?

If you are using Java 17 or later you might try a different garbarge collector, specifically "-XX:+UseZGC"", which you should be able to put in igv_arguments.   I don't have experience with this but one user reports good results.   We can't roll this out generally until we require Java 17.

**Comment by fidibidi** [comment]
Hey Jim, 
I'd say about 10 minutes of scrolling. 

Additional info is that they are presigned S3 links. 

I guess the 32GB logic was sort of based on the notion that more would be better, but good to know that it might actually be detrimental... 

I'll check out the new garbage collector!

**Comment by jrobinso** [comment]
Let us know if the new garbage collector makes a difference, we are interested in it but are still distributing for Java 11.

Its possible there is a memory leak in IGV, in which case GC won't help.   If thats the case then reducing from 32 GB to a lower number like 8 should cause your symptoms much faster.

**Comment by fidibidi** [comment]
Just wanted to note:
Switching to Java 17 + the command, did in fact result in a noticeable performance boost!
IGV eventually slow down, but its also faster on the refresh
