### ISSUE TITLE
gtf file loading error:  'special' file names

### ISSUE THREAD

**Issue by jayoung** [igvteam/igv#1125]
hi there,

I just spent a frustrating couple of hours struggling to figure out why my gtf file wasn't loading correctly. After staring at the file, updating IGV, updating java, restarting my computer, I finally figured out the problem was nothing to do with the contents of the file, rather that the file name included 'ncbiRefSeq' (see https://github.com/igvteam/igv/issues/1051), which means IGV doesn't treat it like a regular gtf file.

My file loaded fine when I renamed it to `test.gtf`, but when the filename was `mm10_ncbiRefSeq_2021_Mar17.sorted.gtf`, I got this error: 
```
Error loading /Volumes/malik_h/grp/public_databases/UCSC/mouse_Dec2011/misc_tracks/mm10_ncbiRefSeq_2021_Mar17.sorted2.gtf: class org.broad.igv.feature.tribble.UCSCGeneTableCodec cannot be cast to class org.broad.igv.feature.tribble.GFFCodec (org.broad.igv.feature.tribble.UCSCGeneTableCodec and org.broad.igv.feature.tribble.GFFCodec are in module org.igv of loader 'app')
```
It's a gtf of NCBI refGenes I had downloaded from UCSC via the Table Browser feature. I didn't know it was a bad idea to name it like I did.

Is there some way to make this error more informative?  Maybe issue a warning before loading the file that it's being processed in a way that expects some sort of non-standard gtf? Then I'd know to rename the file. Or perhaps allow the user to turn off whatever this special processing is?

thanks!

Janet Young
Fred Hutch Cancer Research Center
Seattle, WA USA

**Comment by jrobinso** [comment]
It should not have failed like that, since it has a "gtf" file.  Looking for the magic ncbiRefSeq string should be a last resort guess.   I will look into this and restore the original intent (last resort guess).   

BTW there is no need to use the Table Browser for that table, you can just download the entire table dump in the "Annotations" download and load it as is, i.e. this file https://hgdownload.soe.ucsc.edu/goldenPath/mm10/database/ncbiRefSeq.txt.gz

**Comment by jrobinso** [comment]
Also there are no standards for "gtf" format, or put another way there are multiple standards, and I don't know what conventions UCSC uses.  So that file may or may not behave as you expect wrt constructing a transcript from its parts.  The "bed" format is preferable in this respect, and also much smaller, but again for this table its not necessary to use either.

**Comment by jayoung** [comment]
Thanks, Jim.  Yes, it would be great to restore the original intent.

I had wanted a gtf for some other purpose outside of IGV (long enough ago that I forget what). I have a bunch of those gtf files for different genomes lying around - would be great to use them without renaming.

Janet

**Comment by jrobinso** [comment]
What version of IGV are you using?  You didn't say, so I am assuming it is the latest.

**Comment by jayoung** [comment]
sorry about that - yes, v 2.12.3, on a mac
