### ISSUE TITLE
Support bigGenePred

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#1130]
Support bigGenePred, used for T2T annotations.   This is not genePred, the column layout is closer to bed.  See https://genome.ucsc.edu/goldenPath/help/bigGenePred.html.

Also bigNarrowPeak and bigInteraction

**Comment by jrobinso** [comment]
@maximilianh Yes this looks good, its at the top of my list along with assembly & track hub parsing.  BTW are the NCBI hubs you speak of the "Gen Ark" hubs (https://genome-blog.soe.ucsc.edu/blog/2021/11/23/genark-hubs-part-1/)?    I find the public hub page a little overwhelming, all kinds of stufff in there (this page. https://genome.ucsc.edu/cgi-bin/hgHubConnect)

**Comment by maximilianh** [comment]
The public hubs page is something different. Public hubs have been
submitted by all sorts of labs. We will need to clean up this page and add
hubs groups and/or faceting so people can find hubs again.

The Genark hubs (so currently only NCBI assemblies) are linked from this
page:
https://hgdownload.cse.ucsc.edu/hubs/

(We're preparing a big index page that shows all of them.)

Also, you can find any hub by searching on our main page in the search box
http://genome.ucsc.edu/cgi-bin/hgGateway e.g. you can type "human" there
and find CHM13.
(this page does not make it sufficiently clear that you can search for much
more than the UCSC-genomes... sigh...)

**Comment by jrobinso** [comment]
@maximilianh Its not obvious how to get from the hub URLs, which link to a browser page, to the trackDB.txt and related files,  for example  https://hgdownload.soe.ucsc.edu/hubs/GCA/009/914/755/GCA_009914755.4/trackDb.txt

Maybe I have missed a link but can't find one.    I don't even remember how I managed to to find the link above, some combination of web searching and guessing.   Thee seems to be another trackDb.txt for that assembly (chm13 v2.0) here, but with many fewer tracks:  https://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v2.0/trackDb.txt

WRT bigGenePred and other specialized "bb" formats there is an issue determining format if not given external information.   I had hoped "autoSql.table" would tell me the format but it doesn't.   For example the following stanza indicates a type, which I'm interpreting as format, of "bigGenePred",  however the actual structure differs from what's described for that format and "autoSql.table" indicates the format is "bigCat".   I supposed I can parse the autoSql, which I'm already doing, and infer a format from that.

```
track catLiftOffGenesV1
shortLabel CAT/Liftoff Genes
longLabel CAT + Liftoff Gene Annotations
description CAT + Liftoff Gene Annotations
type bigGenePred
group genes
itemRgb on
maxItems 10000000
maxWindowToDraw 10000000000
priority 1
visibility pack
searchIndex name,name2,txId,geneName,sourceGene,sourceTranscript,alignmentId
labelFields name,name2,txId,geneName,sourceGene,sourceTranscript,alignmentId
defaultLabelFields name
labelSeperator " "
bigDataUrl bbi/GCA_009914755.4_CHM13_T2T_v2.0.catLiftOffGenesV1/catLiftOffGenesV1.bb
html html/GCA_009914755.4_CHM13_T2T_v2.0.catLiftOffGenesV1.html
```

**Comment by jrobinso** [comment]
Never mind first part of the question,  I think I found the magic formula, something like this https://hgdownload.soe.ucsc.edu/hubs/primates/genomes.txt

Determining format (bigGenePred etc) from stanza information or autoSql is still an open question.

**Comment by maximilianh** [comment]
@jrobinso

> Its not obvious how to get from the hub URLs

The hub.txt contains everything, since it has the statement "useOneFile on"
in the first stanza. There is no need for the trackDb.txt file . (I'll ask
why the trackDb.txt file is there at all.)

> Thee seems to be another trackDb.txt for that assembly (chm13 v2.0) here,
but with many fewer tracks:
https://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v2.0/trackDb.txt

This is the hub used by the T2T project itself. It has more tracks, but in
various states of release and probably a lot of outdated tracks. Also, the
tracks do not always have documentation pages.
The webserver where this is hosted is a lot less reliable.

> WRT bigGenePred and other specialized "bb" formats there is an issue
determining format if not given external information.

"external information" ? I don't think we ever had files that are fully
usable without external information... it's an interesting idea, but it may
be too late to have fully self-describing track files, we always have had a
lot of essential information for humans (mouse over fields, color, title,
short names, etc) in an external file.

> I had hoped "autoSql.table" would tell me the format but it doesn't.

The autoSql file tells you the fields. So yes, indirectly, it indicates the
format. But I wouldn't use this to get the data type of track. To get the
data type, it's easiest to look at the "type" field in trackDb, nothing
else.

> For example the following stanza indicates a type, which I'm interpreting
as format, of "bigGenePred"

Exactly. This indicates the format.

> however the actual structure differs from what's described for that format

No, it matches, because all the bigBed-based formats, just like bigBed, can
add additional fields. So a "format" is defined as only the first columns.
"type bigGenePred" is basically a bigBed12+8, with 20 fields, so 8 extra
bigBed fields are used to get the codon display working and a gene symbols
field. You can still add more fields, if you want to show more information
for a particular transcript, just add more fields to autoSql file, at the
end. We use that a lot.

> "autoSql.table" indicates the format is "bigCat"

This is just a descriptive name and not used for display.

> I supposed I can parse the autoSql, which I'm already doing, and infer a
format from that.

I think it's enough to look at the "type" field to get the type. This is
the same for all other tracks, the track data type is indicated by the
"type" key in the trackDb file.

If you have ideas on how to make this easier or how to better document
this, let me know. I had hoped that our docs pages about track hubs
https://genome.ucsc.edu/goldenPath/help/hgTrackHubHelp.html would explain
the concept of track types and then bigGenePred format docs page would be
sufficient to explain the concept of extra fields (the 12+8 thing)
https://genome.ucsc.edu/goldenPath/help/bigGenePred.html but apparently
that's not true...

**Comment by maximilianh** [comment]
Sidenote: did you see this URL on the /hubs html page on
hgdownload.soe.ucsc.edu, with a list of all currently available assembly
hubs (we can add more, just send them to ***@***.***):
https://hgdownload.soe.ucsc.edu/hubs/UCSC_GI.assemblyHubList.txt

**Comment by jrobinso** [comment]
@maximilianh Thanks once again for the detailed response.   Got it.  I think i can use the autoSql field descriptions for users who just load a "bb" file,  i.e. to trackDB or other information telling me the format.    If someone loads a "bb" file with no autoSql I will just treat it as a plain bed.   This should work in 99% of cases.   

RE documentation it is very good in general, and very complete.  The problem could be I'm not a careful reader.    The concept that maybe is not as clear is the distinction between track type and file format.  I am inferring from your clarifications above that a "bigGenePred" track type can be used with any bb "format" that includes at least the fields specified in the bigGenePred format description.   By format I mean a specific list of fields, or autoSql table.    So I do not have to use a bigGenePred file created with bigGenePred.as with a bigGenePred track type.   I can use a superset (bigCat) with that track type as well.    

igv.js has a similar distiction but more explicit. To define a track you specify the track "type" and file "format".   So an alignment track "type" can use "cram" or "bam" formats.     

And I missed the link to assemblyHubList.txt, that's exactly what I was looking for. 

This is all great stuff,  these hubs are a fantastic resource.

**Comment by maximilianh** [comment]
I talked about this with my colleagues and we think that in 99% of the
cases you can determine the bigBed format indeed from the file itself,
using the autoSql string in the file. We never change the names of the
fields, and external contributors neither. so if you see certain names at
certain places in the autoSql (e.g. cdsStartStat) you can relatively safely
guess that it's bigGenePred.

Your thoughts on the difference between track type and data format are
interesting. We should allow this. E.g. have two settings "type bigBed" and
"format bigGenePred" instead of "type bigGenePred". Then the track would
work on NCBI and Ensembl just fine as a bigBed track and only the codons
would be missing.

**Comment by jrobinso** [comment]
Mostly fixed with PR #1140.   The "interact" formats are not yet supported in IGV desktop, although they are in igv.js.   Will open a new issue for that.

**Comment by jrobinso** [comment]
@maximilianh Another bigbed format, autosql table is "bigRmsk", has me puzzled.  This one is used in the chm13 hub.  The schema description is here:  https://genome.ucsc.edu/cgi-bin/hgTables?db=hub_3267197_GCA_009914755.4&hgta_group=varRep&hgta_track=hub_3267197_t2tRepeatMasker&hgta_table=hub_3267197_t2tRepeatMasker&hgta_doSchema=describe+table+schema

In particular, blockSizes and blockStarts can be negative numbers, I've never seen this before.

**Comment by maximilianh** [comment]
Oops. That's a good point. I admit that I didn't pay enough attention when
bigRmsk was developed by @rmhubley. This clearly breaks compatibility with
anyone reading it. Let's see what Robert says and maybe we can move these
to valid bigBed fields. The big* formats should not break the existing
semantics of existing fields...

**Comment by rmhubley** [comment]
First some background.  This data format is inherited from the pre-existing
rmskJoinedTrack that I developed back in 2012.  The blocks stored represent
interwoven aligned/unaligned regions of a sequence model.  The negative
starts represent the unaligned segments whereas the positive ones are the
aligned segments.  The blocksize should always be a positive value ( if you
notice otherwise it's probably a bug in the dataset ).  This extra
encoding is a necessity of the visualization.

While I agree that overloading data structures is a bad idea, I think the
BED format is meant to be extensible if you only commit to conformance over
a portion of the fields.  E.g this is perfectly valid BED3, BED4, BED6, or
even BED9 (if that even exists independently).  I probably should have used
field names like 'notThatBlockCount', 'notThatBlockStart' etc...but I
thought that any confusion could be cleared up in the documentation. If
there is a simple way that this could be encoded with less confusion, I am
happy to make changes, but my bandwidth is quite limited these days.

-R
