### ISSUE TITLE
Wrong coordinates after changing reference genome on Windows11

### ISSUE THREAD

**Issue by ATpoint** [igvteam/igv#1132]
Hi,
I am on Version 2.12.3 03/04/2022 3:20 PM on Windows11. It seems the IGV fails to properly update the coordinate system after switching from mm10 to mm9. When I enter gene names such as "Gapdh" it will track me to the mm10 coordinates, basically making navigation by gene name impossible. Am I doing sth naively wrong? On macOS and Linux that always used to work properly after switching reference genome.

Here two screenshots, both times going for "Gapdh" in the search field.

![mm9](https://user-images.githubusercontent.com/21218078/162469250-c127812f-c05b-47d1-82e4-2b0ad9ce4c49.png)
![mm10](https://user-images.githubusercontent.com/21218078/162469259-e9b4d8c2-09ba-45b7-b38f-4edf80263d54.png)
?

**Comment by jrobinso** [comment]
Yes, I can reproduce this.     Its a bug, I'll put it on the priority list and deploy a fix asap.   In the meantime you will need to restart IGV after changing genomes.   Apologies for the inconvenience.

**Comment by jrobinso** [comment]
Actually on further investigation the problem was with the mm9 genome definition, it was using mm10 coordinates.  It had nothing to do with switching genomes.   The genome definition has been updated, if you re-download mm9 from the server it should be fixed.   You can do this by going to "Genomes > Select Hosted Genome..." and select Mouse (mm9).

**Comment by ATpoint** [comment]
I see, thanks for the prompt reply!

**Comment by ATpoint** [comment]
Can confirm that the issue is solved with the re-download of the genome, thank you!
