### ISSUE TITLE
Would IGV show base modifications at insertions?

### ISSUE THREAD

**Issue by elcortegano** [igvteam/igv#1303]
I'm currently using IGV 2.16.0 to visualize base modifications in PacBio HiFi reads, i.e. 5mC modifications at CpG sites predicted by primrose.

It is unclear to me however if these modifications are shown for insertions, as I cannot seem to find any 5mC modification at insertions containing CpG sequence. One example is shown below:

![Screenshot from 2023-03-22 11-15-20](https://user-images.githubusercontent.com/57492899/226889247-8b94b8af-3578-4afc-9f0b-2da67f6f5e29.png)

Does this happen because insertions with CpG sequence in my data are genuinely not methylated, or is it that IGV is not showing base modification for them? If this were a IGV limitation, is there a way to overcome it, or any plans to include this in IGV?

Thank you

**Comment by jrobinso** [comment]
IGV is not showing them for insertions.  I think this should be possible,  but could you provide a small test set?

**Comment by elcortegano** [comment]
Sure, I could prepare a small test. Where should I submit it?

**Comment by jrobinso** [comment]
You can zip and attach it here,  or send email to igvteam (at)
broadinstitute.org and I will send you a dropbox link to upload to.   Or
put it in dropbox or similar and send us a link.

**Comment by elcortegano** [comment]
Just checking you received my email, I sent one past Saturday 25.

If you only need the BAM files, I can upload some here. If the reference is also needed, I'd prefer to submit those more confidentially.

**Comment by jrobinso** [comment]
Yes, sorry for the delay.  You should receive an upload request from
dropbox, use that link to upload the files.   I don't know if the reference
is needed or not until I look into it more deeply.

**Comment by jrobinso** [comment]
BTW there is a third possibility, that modifications were not called there.   If the software is only calling sites that are C/G in the reference, for example, there will be no calls for these bases.     Do you know if Primrose makes calls at sites that are not CpG in the reference?

**Comment by jrobinso** [comment]
This is orthogonal to the issue you raise, IGV would not display them even if they were called, but I am a little bit unsure that they are.

**Comment by ctsa** [comment]
> BTW there is a third possibility, that modifications were not called there. If the software is only calling sites that are C/G in the reference, for example, there will be no calls for these bases. Do you know if Primrose makes calls at sites that are not CpG in the reference?

Primrose makes 5mCpG calls on unaligned reads, so the MM/ML tags represent methylation across the entire read. It should not matter if the read mapper has aligned a segment as inserted, clipped or left the whole read as unmapped.

**Comment by jrobinso** [comment]
@ctsa Good to know, thanks.  I understood this to be the case, but I wasn't sure if the software recorded these calls in the final BAM output.

**Comment by elcortegano** [comment]
I have prepared some BAMs that should contain insertions involving new CpG sequence, near to 5mC CpG sites ([BAMs.zip](https://github.com/igvteam/igv/files/11130362/BAMs.zip)).

I you need the FASTA for the reference, I'll try to set a dropbox link (I did not receive the upload request).

**Comment by jrobinso** [comment]
@elcortegano I'm not sure what happened, but I resent it directly from our igvteam email.

**Comment by jrobinso** [comment]
Update on this -- its important but complex, the approach for painting expanded insertions needs redesigned.  Its on my project list here but I don't have an estimate for completion yet.

**Comment by jrobinso** [comment]
OK long time coming, but expanded insertions has been completely redesigned which, as a side effect, made this doable.  There is no coverage pileup for an insertion, so consequently no pileup of modifications.    "Coverage" for insertions is tricky because unless they are aligned (with the "P" cigar tag), the placement of individual bases with respect to other alignments is arbitrary.   In the example from your dataset the insertions are all the same length so they pileup nicely,  in general this is not the case.   I don't think I've ever seen a "P" operator in a cigar string in a bam file,  only in the SAM specification example.

This will be in the next release, by the end of September, and now in the nightly snapshot build.

<img width="1018" alt="Screen Shot 2023-08-31 at 10 03 08 PM" src="https://github.com/igvteam/igv/assets/933148/f909234e-cac0-44dd-9cbb-e1b6b0ba7e98">

**Comment by jrobinso** [comment]
Here's an example of insertions at the same location of different length,  not aligned with "P"

<img width="419" alt="Screen Shot 2023-08-31 at 10 14 03 PM" src="https://github.com/igvteam/igv/assets/933148/7fe5ffe3-fd21-489e-9a25-7a5e2352ffa6">

**Comment by elcortegano** [comment]
Thank you for the update @jrobinso , and for developing this new feature. It looks awesome, and I'm really looking forward to use it.

**Comment by is01** [comment]
I'm so glad this feature was added. 

This really worked for me with nanopore modBAM files.
But a error occured when supplementary alignments are present in the drawing area.
When I set "Base modification 2-color" mode and view the insert array, I get the following error:
<img width="50%" alt="SCR-20230502-nedr" src="https://github.com/igvteam/igv/assets/95663289/b9e9ca21-a5f4-403c-bf4e-c8a14e512907">


The problem was solved by filtering the supplementary alignments.
I hope this error will be fixed in the future releases.

Thanks,
Erina

**Comment by jrobinso** [comment]
There's not enough information in the screenshot to diagnose the problem.

**Comment by is01** [comment]
I checked and there are some secondary/supplementary records that do not contain MM tags in modBAM, which seems to be the cause of the error.

Here's how to reproduce the error:

1. Load the following small SAM file into IGV snapshot. This is a SAM file with the extension changed to .txt.
[chr2_1631887-1744515_extract.sam.txt](https://github.com/igvteam/igv/files/13520820/chr2_1631887-1744515_extract.sam.txt)
2. Go to chr2:1,707,128 and expand the 124bp insertion.
3. Set color to "Base modification 2-color"

This is my error screen:
![image](https://github.com/igvteam/igv/assets/95663289/7a828435-0f26-4b1c-aee9-6e7a3ec318bc)

Please let me know if any information is missing. Thank you!

**Comment by jrobinso** [comment]
Thanks for the detective work and test data, I just pushed a fix for this.
