### ISSUE TITLE
Support for AWS Identity Center SSO Credentials

### ISSUE THREAD

**Issue by kcibul** [igvteam/igv#1333]
Hi Team!

It appears that using AWS SSO credentials to access data in S3 buckets isn't working at the moment.  When attempting to load a resource from S3, you get the following error:

```
SEVERE [May 19,2023 17:01] [DefaultExceptionHandler] software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(): To use Sso related properties in the 'default' profile, the 'sso' service module must be on the class path., ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Unable to load credentials from service endpoint.]
```

The fix is straightforward (and given in the error message actually):

```
 ProfileCredentialsProvider(): To use Sso related properties in the 'default' profile, the 'sso' service module must be on the class path
```

I believe the fix is to include the following in the IGV build.gradle:

```
            [group: 'software.amazon.awssdk', name: 'sso', version: '2.16.7']
```

I tested this by copying the jar from the new dependency (`sso-2.16.7.jar`) into the `/Applications/IGV_2.16.1.app/Contents/Java/lib` and relaunched IGV.  Upon startup it declares:

```
INFO [May 19,2023 17:04] [AmazonUtils] AWS default credentials found. AWS support enabled.
```

And loading data from S3 works as expected.

PR at #1334

**Comment by jrobinso** [comment]
Thanks for the report and PR.  Has this worked in the past for you?  I'm curious to discover what changed.   @brainstorm any comments?

**Comment by brainstorm** [comment]
Sure, this change supports SSO when using on-disk credentials (should not affect Cognito as it doesn't rely on those).

In other words, `~/.aws/credentials` has different attributes and structure when you have plain ACCESS_KEY_ID/SECRET_KEY_ID than with SSO, where you have a token and other auth-related bits, the SDK has to know how to interpret those. 

It worked before because there was no key rotation nor SSO, so I can only guess that folks using the non-Cognito route where just using static infinite lifetime keys.

With Cognito that's all done automatically via the default credential provider chain, keeping refresh token away and handling those mostly in-memory, afaik.

With on-disk "classic" credentials, there's no key rotation (unless DIY'd). With SSO there is a step up on security, so that's a welcome change, but there's still a few gaps that one needs to DIY that Cognito provides as-is 🤷🏻

**Comment by kcibul** [comment]
Hey @brainstorm  -- we're not doing anything special other than using IAM Identity Center for SSO to assume roles across accounts for our computational biology team (who needs native AWS access for spinning up instances, etc).  We're not using Cogito at all at the moment.  I'd be interested in hearing more about why you think Cogito is superior to Identity Center.

I might have misunderstood in what you said -- but SSO is still provided via the default credential provider chain, it's just that the necessary libraries (jar) was missing from the IGV distribution to support that.

**Comment by jrobinso** [comment]
OK, this will be included in the next release, which we are wrapping up in the next few weeks.  @kcibul If this is needed quicker we could do a point release with just this change.

**Comment by brainstorm** [comment]
> (...) roles across accounts for our computational biology team (who needs native AWS access for spinning up instances, etc). (...)
> I'd be interested in hearing more about why you think Cogito is superior to Identity Center.

One of the reasons: I can only guess that you are using the IAM role/policies that users use for CLI and general AWS use for IGV access as well? If that's the case, you are giving permissions to spin instances and do other things to purposes that are not germane to IGV, instead of separating concerns.

With our current Cognito setup you would not have that (security) issue. Plus endpoint threats don't usually scan (java) process memory (Cognito approach) unless highly targeted... as opposed to plenty of `~/.aws` vacuuming malware (supply chain attacks on PyPi, npm, etc... nowadays).

OTOH, being Broad, I bet you have this figured out well already, so kudos for this very simple and valuable SSO change (honestly), that's a very welcome improvement over static IAM creds! ;)

**Comment by kcibul** [comment]
No rush @jrobinso -- but will be nice to have this in a release, mostly we have Mac users so the launchable App is nice

@brainstorm -- yep, I see what you're getting at there with Cognito I'll have to think about that.  Thanks for the explaination!
