### ISSUE TITLE
Feature request: add support for DRS URIs

### ISSUE THREAD

**Issue by bheavner** [igvteam/igv#1377]
NIH cloud service providers (such as AnVIL and BioData Catalyst) are adding support for [GA4GH DRS URIs](https://www.ga4gh.org/news_item/drs-api-enabling-cloud-based-data-access-and-retrieval/). It would be wonderful if IGV could use them as pointers to genomic data files.

**Comment by jrobinso** [comment]
The first step would be to have working, stable, publicly accessible test URLs.

**Comment by DanBiber** [comment]
Gen3 has drs_uris currently incorporated into our BDC data model.  I have attached a delimited file with drs_uris that link open access CRAM files to CRAI files.  I attached a simple tutorial notebook that utilizes Gen3 APIs that can be iterated on if users have additional access.  Github doesn't currently allow for .ipynb files but don't hesitate to ask for it and I'm sure I can get it to you.
[open_access_drs_uri_pairs_query.pdf](https://github.com/igvteam/igv/files/12622310/open_access_drs_uri_pairs_query.pdf)
[open_access_drs_uris.csv](https://github.com/igvteam/igv/files/12622311/open_access_drs_uris.csv)

**Comment by jrobinso** [comment]
Thanks @DanBiber.  A notebook would be educational.   I keep my notebooks in github, but perhaps you mean you can't attach them?  You should be able to zip and upload the zip.

**Comment by DanBiber** [comment]
Thanks!  I didn't think about zipping it.
 [open_access_drs_uri_pairs_query.ipynb.zip](https://github.com/igvteam/igv/files/12622988/open_access_drs_uri_pairs_query.ipynb.zip)

**Comment by jrobinso** [comment]
Just getting into this.  To load a file into IGV we eventually need to get to an http/https url.  I'm starting with the files in the csv file above.   An example is below, this looks like a mistake, with prefix listed twice

```
drs://dg.4503:dg.4503/a5d35aac-ec73-46cc-9fb0-13503717aac4
```  

Shouldn't this be ?

```
drs://dg.4503/a5d35aac-ec73-46cc-9fb0-13503717aac4
```

Calling the registry APi twice I can eventually get a response with gs:// and s3:// URLs to the cram file.  IGV can handle the gs:// URLs as there is a documented conversion to an https:// endpoint.   This is not true of the s3:// URLs.   IGV can handle those if the end user has AWS credentials by calling an Amazon service,  otherwise there is not (I think) an s3 -> https conversion.

**Comment by jrobinso** [comment]
Oh never mind I see my mistake, prefix is `dg.4503`, accession is `dg.4503/a5d35aac-ec73-46cc-9fb0-13503717aac4`

**Comment by jrobinso** [comment]
@DanBiber Are the n2t urls expected to work with these urls?  I'm following the examples here: https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.2.0/docs/#section/Calling-Meta-Resolver-APIs-for-Compact-Identifier-Based-DRS-URIs

This returns "not found"

```
https://n2t.net/dg.4503:
```

**Comment by jrobinso** [comment]
The example 1kg files here are not public,  the Google urls (gs://) are in "requestor pays" buckets, and the s3: urls return "access forbidden" with my credentials.   So some progress has been made but we are back where we started,  no publicity accessible stable URLs to test with.   I guess I shouldn't generalize, I only tried one.

**Comment by Avantol13** [comment]
Hi @jrobinso , our DRS implementation uses identifiers.org as the registry, not n2t. So you can resolve like this: https://registry.identifiers.org/registry/dg.4503

Some files require authentication even though they're open (open access data but identification is required). Can you explain exactly what DRS URI you're trying to resolve and how? If you want to access the data you need to use the DRS access methods, you can't just read the file in the bucket. Gen3 instances generally support signed URLs as the mechanism to get a file. 

You need hit /DRS_ID/access/s3 I believe. The DRS spec specifies the way to find and use access methods

**Comment by jrobinso** [comment]
You can see the steps I took to obtain URLS in this notebook: 
 https://colab.research.google.com/drive/1Htza04u9VtmR8DAGSw13clVx4nTp9dIJ.    I was following the spec documents referenced above.  This procedure does not appear to be "automatable" to me,  it feels like human eyes are required to get the info needed.   For example in this step from the notebook

```
urlPattern = info["_embedded"]["resources"][0]["urlPattern"]
```

For the example in the notebook I was presented a "requestor pays" bucket error for the gs:// url, and a 403 when I tried to fetch a signed urls from the s3:// url.

At this point I think I need to ask @bheavner what exactly he had in mind for IGV.   I envisioned a straightforward mapping from DRS url -> url to the actual file (https, gs, or s3),  but based on this experiment I'm not sure that is possible.

**Comment by Avantol13** [comment]
https://gen3.biodatacatalyst.nhlbi.nih.gov/ga4gh/drs/v1/objects/dg.4503/c64fded3-459b-4fca-82bc-35d154e9aa91

is the DRS record endpoint. You can't automatically access the files in the bucket because even though they're open access, they require you to use an approved DRS access method (which in this case is a signed URL). 

In the response you can see 2 access methods. If you want the s3 file for example, you need to hit the DRS Access endpoint  https://gen3.biodatacatalyst.nhlbi.nih.gov/ga4gh/drs/v1/objects/dg.4503/c64fded3-459b-4fca-82bc-35d154e9aa91/access/s3

Where you'll get a signed URL which should resolve and stream  the file.

**Comment by jrobinso** [comment]
OK, thanks.  Where is the "DRS Access endpoint"  in the DRS spec?   This is the "objectInfo" response from my notebook.   

```
{
  "access_methods": [
    {
      "access_id": "gs",
      "access_url": {
        "url": "gs://nih-nhlbi-biodata-catalyst-1000-genomes/CCDG_14151/Project_CCDG_14151_B01_GRM_WGS.cram.2020-02-12/Sample_HG03197/analysis/HG03197.final.cram.crai"
      },
      "region": "",
      "type": "gs"
    },
    {
      "access_id": "s3",
      "access_url": {
        "url": "s3://nih-nhlbi-biodata-catalyst-1000-genomes-high-coverage/CCDG_14151/Project_CCDG_14151_B01_GRM_WGS.cram.2020-02-12/Sample_HG03197/analysis/HG03197.final.cram.crai"
      },
      "region": "",
      "type": "s3"
    }
  ],
  "aliases": [],
  "checksums": [
    {
      "checksum": "7aa39824444f8c21c7c8e0c42e45aa34",
      "type": "md5"
    }
  ],
  "created_time": "2020-10-02T16:08:49.455887",
  "description": null,
  "form": "object",
  "id": "dg.4503/a5d35aac-ec73-46cc-9fb0-13503717aac4",
  "mime_type": "application/json",
  "name": "",
  "self_uri": "drs://dg.4503:a5d35aac-ec73-46cc-9fb0-13503717aac4",
  "size": 1311059,
  "updated_time": "2020-10-02T16:08:49.455894",
  "version": null
}```

**Comment by bheavner** [comment]
@jrobinso I'm coming from a user perspective, so am fairly naive about the authentication/implementation details - my end goal is perhaps what you imagined, too: I'd like to add a track to my IGV session using a DRS URI, similar to the way I can add a track with an s3:// or gs:// URI now. At the moment, my use cases include me having authorization and the ability to work with files in the ANVIL and/or BioData Catalyst environments, so there's some authorization/authentication process that's enabling that. I have a google cloud billing account, so can assign charges for a requestor pays bucket in google cloud, and have successfully used IGV to view tracks with that.

**Comment by jrobinso** [comment]
@bheavner OK,  I assumed that was your goal.  At the moment its not clear to me that this is possible.

**Comment by jrobinso** [comment]
@bheavner You can hopefully get gs or s3 urls easily from the services you use that implement DRS,  and use those with IGV.  What's not clear yet is if its possible to automate this.

**Comment by jrobinso** [comment]
@bheavner OK I have an update on this.   Some colleagues at the Broad pointed me to a DRS resolver webservice they run
https://drshub.dsde-prod.broadinstitute.org/

This service resolve DRS urls to loadable signed URLs.   I have verified it works for Terra urls.  It does return something for for the URLs in your CSV but they are not signed URLs.  I can't test them because they are in "user pays" buckets.  However perhaps you can,  could you try to load these into IGV?  You will need to enter both cram and index url.  And you will need to have set your Google project in IGV (I assume you've done that already)

Cram
```
gs://nih-nhlbi-biodata-catalyst-1000-genomes/CCDG_14151/Project_CCDG_14151_B01_GRM_WGS.cram.2020-02-12/Sample_HG03197/analysis/HG03197.final.cram
```

Index
```
gs://nih-nhlbi-biodata-catalyst-1000-genomes/CCDG_14151/Project_CCDG_14151_B01_GRM_WGS.cram.2020-02-12/Sample_HG03197/analysis/HG03197.final.cram.crai
```

**Comment by bheavner** [comment]
Yes, after logging in with my google credentials, I can see those!

**Comment by jrobinso** [comment]
@bheavner OK this should work then.    I hope to have it in the next release, which is later this month.   I should have a build you can test before then.   I'll update here.

**Comment by bheavner** [comment]
Very cool. Thanks, Jim!

**Comment by jrobinso** [comment]
@bheavner Unfortunately the initial success was a false alarm.  The service used in the test (from the Terra project) is not available to IGV.  At the moment there doesn't appear to be any services callable by IGV to resolve DRS urls,  and for that matter no documented means to do so.   So, again unfortunately this doesn't seem possible.
