### ISSUE TITLE
Error querying alignments for: alignment.sort.bam Error message: Invalid GZIP header

### ISSUE THREAD

**Issue by daniel-es6** [igvteam/igv#1410]
Hello, 

I am getting this error when loading a bam file that is sorted and indexed. I have tried to delete all the index bai files and recreate it, but still no success. What can be wrong?

The IGV version is 2.16.2, desktop version on a mac (intel chip).

Thanks

**Comment by daniel-es6** [comment]
samtools view opens the bam file without problems.

**Comment by jrobinso** [comment]
Is this being loaded locally or from a web server?  If the latter,  one possible cause is the web server improperly adding a "Encoding: gzip" header to the response.   I have seen this happen and it will cause the error you are experiencing.    Otherwise I couldn't really say.  If you could share the BAM file we will look into it.

**Comment by daniel-es6** [comment]
Hi Jim, I found it was caused by a sync problem, I was opening the old bam file. After a clean sync, the problem went away. Thank you for the tip

**Comment by daniel-es6** [comment]
solved.
