### ISSUE TITLE
IGV: Unexpected Error Repainting view

### ISSUE THREAD

**Issue by santataRU** [igvteam/igv#1617]
Dear IGV Developers,

I am currently using IGV version 2.18.4 on macOS with an M3 chip. While attempting to view a GFF file for a custom genome, I encountered an error stating: "Unexpected Error Repainting View."

To help reproduce and diagnose the problem, I have shared the relevant files, including the IGV log and a screen recording of the issue.

I would greatly appreciate your guidance in resolving this matter.

Best regards,
Xiao

Link to access the files: https://drive.google.com/drive/folders/19YdYuLIyNeUBoBv9HQcj-oECQ2qplax4?usp=sharing

<img width="1290" alt="Screenshot 2024-11-15 at 5 20 35 PM" src="https://github.com/user-attachments/assets/04b8bdbd-0ebc-46a9-895a-272457abc04a">

**Comment by santataRU** [comment]
Thank you for fixing this! Could you please let me know where I can download the updated version of IGV?

Best regards,
Xiao

**Comment by jrobinso** [comment]
Thanks for the test files, it makes it much easier to debug.   This was due to a parsing error in IGV, its very surprising we haven't encountered this before.    The fix will be included in the next release at the end of the month,  if you need it in the meantime you can use the development snapshot build.   You can download this build at https://igv.org/doc/desktop/#DownloadSnapshot/.

**Comment by jrobinso** [comment]
I should have added that the snapshot view is built daily,  I will start a build now and it should be available within an hour.

**Comment by jrobinso** [comment]
Ok snapshot is built https://igv.org/doc/desktop/#DownloadSnapshot/

**Comment by santataRU** [comment]
> Ok snapshot is built https://igv.org/doc/desktop/#DownloadSnapshot/

Thank you very much for your effort!
