### ISSUE TITLE
Zoom in/out problem with pacbio reads

### ISSUE THREAD

**Issue by fritzsedlazeck** [igvteam/igv#219]
Hi,
I really like IGV and use it on a daily bases. However, when I load long reads (e.g. PacBio) and want to zoom out from a region I observe often that IGV almost crashes. Usually I can restart IGV and it seems to be fine again, but I just tested the new version and there I am not even able to stop IGV. 
Could you please look at this?

Thanks

**Comment by jrobinso** [comment]
> On Mar 30, 2016, at 8:22 AM, Fritz Sedlazeck <notifications@github.com> wrote:
> 
> Hi,
> I really like IGV and use it on a daily bases. However, when I load long reads (e.g. PacBio) and want to zoom out from a region I observe often that IGV almost crashes. Usually I can restart IGV and it seems to be fine again, but I just tested the new version and there I am not even able to stop IGV. 
> Could you please look at this?
> 
> Thanks
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/igvteam/igv/issues/219>


Hi,

I’m not sure what your issue is with stopping IGV as I don’t know how you normally do it.   WRT pacbio reads, they are challenging as they take huge amounts of memory to fully load.   I am working on this problem, and have some partial solution but it is not yet released.   You can try it however by following the steps below.  The “reduced memory mode”  drops SNP information and small indels,  usually not important when you zoom out.   These options were suggested by pacbio engineers,  who worked with me on implementation.   

Prior to release there will be a means of switching to/from this mode from the menus,  currently you have to restart IGV and cannot switch to/from this mode during a session.

Jim


(1) shutdown IGV

(2) edit the "prefs.properties" file located in  <user home>/igv  and add the following lines

SAM.REDUCED_MEMORY_MODE=true
SAM.MIN_INDEL_SIZE=25
SAM.MAX_VISIBLE_RANGE=3000    (i.e. 3,000 kb or 3 mb,  this is max window for which alignments are loaded, increase or decrease as desired)

(3) start IGV and load bams as usual.



-- Jim

**Comment by jrobinso** [comment]
Ping -- did the suggestions outlined above help with your problem?

**Comment by fritzsedlazeck** [comment]
Sorry I still have to test this. 
I am currently using a Mac, is there a way to modify it?
Thanks

**Comment by jrobinso** [comment]
No problem, but sorry modify what?

**Comment by fritzsedlazeck** [comment]
You told me to edit the "prefs.properties" file. For Mac, however, I usually just download the java img. So is it possible to make the edits somehow?

**Comment by jrobinso** [comment]
Yes, it is in the same place, under your home directory in an "igv" 
folder.   It should be there if you have run  IGV before on that computer.
