### ISSUE TITLE
IGV Port Command: Sort and Color by

### ISSUE THREAD

**Issue by egafni** [igvteam/igv#228]
We make heavy use of IGV Port commands to generate images on the fly for manual investigation of questionable alignments in our clinical samples at Invitae.  Not being able to sort and color alignments (particularly by read strand) has been a big limitation for us.  

I am having problems with both the sort command, and the setting the color_by preference:

I can only turn read-strand coloring on by setting it in the preference file when IGV is first launched;  If I try to port-command `preference SAM.COLOR_BY READ_STRAND`, IGV does not recognize it.

Additionally, the port command `sort strand` is not sorting the reads.

I'm using IGV version 2.3.72
Here's the full sequence of commands:

```
SEND: goto 2:47669483-47669561
RECV: OK
SEND: preference SAM.SHOW_SOFT_CLIPPED false
RECV: OK
SEND: preference SAM.COLOR_BY READ_STRAND
RECV: OK
SEND: sort strand
RECV: OK
SEND: snapshot 147.png
RECV: OK
```

**Comment by egafni** [comment]
Sorry! I see now that this is a preference setting. Please ignore :)

**Comment by jrobinso** [comment]
Hi,  all these commands, including sort strand, are working as expected for me.    The preferences need to be set before the alignment track is loaded.    Also note that the sort command sorts rows of alignments based on the value of the sorted property at the center of the view  (marked by a center line if you have that turned on).   If this is not occuring for you post a screenshot,  I might also need some sample data since I can't reproduce this.

**Comment by egafni** [comment]
Thanks!!! Loading after setting the COLOR_BY preference did the trick.  Sort by strand is working too, that was my mistake, so sorry about that.  Really appreciate the quick feedback, our production biofx team will be very happy to see this.
