### ISSUE TITLE
Support for 10X linked reads

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#275]
This is an open issue for discussing enhanced support for 10x barcoded BAM files.  As a starting point we'll aim to implement support for a "Loupe" style phased/linked read view by leveraging the existing group & color-by options with the 10X Bam tags described here:  http://software.10xgenomics.com/genome-exome/pipelines/latest/output/bam.

**Comment by jrobinso** [comment]
Question:  Is there any way to determine from the BAM header if a file contains 10X data?   I see the following entries in my test file, will any or all of these reliably be present?

@PG       PN:longranger.lariat	ID:lariat
@PG	PN:longranger.mark_duplicates	
@PG	PN:longranger.attach_phasing	
@PG	PN:longranger	ID:longranger

**Comment by cwhelan** [comment]
This looks great so far. One question: the colors of the reads in individual barcodes seems to shift a little bit as I browse around, with various shades of yellow/red in HP 1 and blue/purple in HP2. Is the shifting color encoding something?

**Comment by jrobinso** [comment]
That's a "know issue" which I will fix.  Its actually doing a complete repaint continually as you pan, and is rechoosing colors randomly for each linked read.   That's disconcerting,  I will do something to make that stable.   Its not encoding anything.

**Comment by cwhelan** [comment]
One thing that might be useful would be to specify a cutoff for maximum gap between reads, after which reads could get grouped into different linked-read lines. I believe that 10X's molecule inference algorithm doesn't link reads with a gap greater than 50kb, for example, so by setting a maximum gap of 50kb you could reproduce their results.

**Comment by cwhelan** [comment]
Maybe I'm just missing it but is the 'sort by max gap' feature you show in the slides available in the snapshot build? I don't see it when I right click and open the 'sort alignments by' sub-menu.

**Comment by jrobinso** [comment]
That’s experimental, but it should be doing it automatically if you select the “linked reads” view.   The idea was to get all the linked reads with “large gaps” between individual reads together.   So it sorts the packed rows by the maximum gap (between individual reads with same barcode) size in that row.   I’m not sure this is the best way to do it,  an alternative metric might be just the total mapped length of the “linked read”.   I’ve also experimented with color-coding by length of the read.

BTW I’m working off called variants from the sample NA12878 dataset from 10X,  this lets me compare what I’m seeing with Loupe.    The deletions are clear enough,  but the duplication and inversions (there aren’t many) are not overwhelmingly convincing.

**Comment by jrobinso** [comment]
Chris, I don't quite get the logic for maximum gap.  Wouldn't you loose evidence for deletions?  If there's a 100kb deletion and a molecule spans it,  wouldn't there be a 100kb gap, at a minimum, between reads that span the deletion point?

**Comment by cwhelan** [comment]
You're right, the adjustable max-gap suggestion is actually not super useful for SVs. There are two things it could be good for:

1) For SNP phasing, 10X's algorithms do an inference step from barcodes -> molecules. These are assumed to be different molecules that share the same barcode because they came from the same droplet or GEM. They place a molecule identifier in the MI tag in the reads. I believe that part of this involves cutting off molecules when there is a gap larger than 50kb. At least that's what they described in their Nat. Biotech paper. So there's a possibility that you might be linking together reads that were assigned different molecule identifiers by 10X's software. Again, for SVs this is fine and they do all their SV calling by barcode overlap, not molecule identifiers. But if some IGV user wanted to visualize the molecules that went into phasing they might want to send this param.

2) The other reason you might want to set a cutoff for max gap is because in some data sets we've seen piles of reads that appear to spuriously be aligning to simple repeats, far away from any clusters of reads that share the same barcode. I believe that these are artifacts from the sample prep. If you happen to be close (but not too close) to one of these piles of reads, you'll see what looks like lots of long molecules that are driven by these artifacts.

How are you determining the molecule extents right now? You must be using some sort of cutoff on distance, right? Or does anything within the alignment visibility window get sorted into the displayed barcodes?

Anyway, this isn't necessarily a show-stopper if it's hard to implement, just brainstorming on something.

**Comment by jrobinso** [comment]
I think for the first case we should just optionally link reads with the "MI" tag.     Eventually there will be more configuration options,  for the time being I will add a new item  "View linked rides (MI)"  so we can see how well it works.

But yes we can add a max cutoff.   At the moment there is no explicit cutoff, everything loaded (i.e. in view +/- a little) is used.   

I will open a new git issue for adding the cutoff.   This issue will be kept permanently open for discussion, but as we get consensus on concrete items let's track them in separate issues.

**Comment by jrobinso** [comment]
@cwhelan I added a new menu item,  "View linked reads (MI)" to link them by molecular id.  That should directly address (1) above.   However, in doing so I realized that its possible for 2 reads with the same barcode to have different MI tags, and consequently (I assume) different haplotypes.    So the grouping you see in IGV by haplotype might be incorrect for the longer linked reads when grouped by barcode.  I suppose the right thing to do here would be to throw those linked reads into the unknown haplotype category, i.e. the bottom "gray" region, when viewing linked reads by barcode.  Is that correct?

**Comment by jrobinso** [comment]
Oops, never mind,  alignments are grouped first then linked, so haplotype grouping should be correct irrespective of MI and BX tags.

**Comment by cwhelan** [comment]
When I was experimenting with similar things myself I ended up created a "mixed" haplotype category, so I had molecules where all reads in HP1, another for HP2, another for no HP, and a fourth for "mixed".

**Comment by jrobinso** [comment]
That's another possibility.   In the current implementation the reads will get segregated by haplotype first,  then linked, so the mixed haplotype situation will not arise although you might get a "linked" read  in each of the 3 categories all with the same barcode.

**Comment by jrobinso** [comment]
I just pushed the change to "link then group".  It makes a difference for larger SVs, obviously.   Attached is before and after pngs for an inversion (before is group_then_link, after link_then_group)
![group_then_link](https://cloud.githubusercontent.com/assets/933148/16815484/d72c9e52-48ee-11e6-9758-b089af4c6146.png)
![link_then_group](https://cloud.githubusercontent.com/assets/933148/16815489/dd7cb986-48ee-11e6-8953-13e40facd498.png)

**Comment by sjackman** [comment]
@jrobinso Hi, Jim. Is this 10x linked reads feature in IGV 2.3.90? It looks great!

**Comment by sjackman** [comment]
Answered my own question. No, it's not in the stable release, but it is in the snapshot build. Thanks, Jim! I look forward to seeing this feature in a stable release.

**Comment by sjackman** [comment]
Is there an option (or could there be) to display a physical molecule coverage track?

**Comment by sjackman** [comment]
Is it possible to increase the distance between the molecules, to make it easier to tell where one molecule stops and the next starts? Could the thin line joining reads be made thicker, perhaps 50% the thickness of a read?

**Comment by jrobinso** [comment]
Hi Shaun,  I don't understand the first part.  The molecules are where they
are,  how could we increase the distance?

**Comment by sjackman** [comment]
Hi, Jim. I meant increase the spacing between molecules by choosing a different vertical layout of the molecules. For example, it's difficult to quickly tell that there are four molecules here.
```
x---x---x x---x---x x---x---x
              x---x---x
```
Contrast with the following layout.
```
x---x---x     x---x---x
          x---x---x
                    x---x---x
```
Possibly achieved by adding a buffer space to the end of each molecule, and layout the reads so as to avoid placing reads in that buffer space. It takes more vertical space, but is easier to interpret.

**Comment by jrobinso** [comment]
OK, I get it.  The buffer is a difficult thing BTW.  You can set a buffer
in base pairs or pixels.   If you use pixels you have to redo the layout at
every zoom, and more importantly the view is unstable.  So if I'm looking
at something and zoom in it's suddenly gone because the alignments are all
rearranged.   But I understand the intent.

**Comment by sjackman** [comment]
Yeah, I see the challenge. I'm okay personally with the layout being unstable to zooming (unless of course zooming were smooth with a scroll wheel) so long as a single read can be selected and have that read remain in focus through zooming. A buffer set in base pairs would still be useful though.

**Comment by sjackman** [comment]
The default zoom factor of IGV is 2.31; where does that number come from? Just curious.

I was thinking a compromise for the buffer zone would to set a nominal buffer size in pixels. For the current zoom level, calculate the buffer size in bp. When the user changes zoom levels, recalculate the buffer size in bp, and if it differs from the current buffer size in bp by more than some factor (say 5x), update the layout, otherwise reuse the current layout. That way it'll reuse the current layout for small changes in zoom, and update the layout for large changes in zoom, for example every second push of the zoom button.

**Comment by sjackman** [comment]
I'd like to be able to separate all the reads from a set of barcodes that I'm interested in. These barcodes are involved in a putative structural rearrangement. Would you consider adding a `Select by BX/MI tag` feature similar to `Select by name`? Even more useful I think would be to separate those barcodes out into their own pane.

**Comment by jrobinso** [comment]
@sjackman @cwhelan I'm doing a cleanup of open issues,  as this one is 2 years old I want to ask if its still relevant before spending time on it.   By "this" I'm referring to the last request from Shaun, dated May 30,1017.   If it is please open a new issue,  its hard to deal with these long discussions touching many topics.
