### ISSUE TITLE
Improper alignment packing at low zoom

### ISSUE THREAD

**Issue by amwenger** [igvteam/igv#301]
When zoomed out, adjacent read alignments often are drawn on top of each other.  This is easiest to see when the alignments are colored as below, which shows a standard Illumina dataset at 4kb zoom with alignments colored by strand:

![screen shot 2016-08-09 at 5 49 26 pm](https://cloud.githubusercontent.com/assets/7155109/17538521/10e6b84a-5e5b-11e6-943b-00805998e536.png)

With ideal packing, there would be 5px or so of white space between adjacent alignments, as is seen for the same locus as above but at high zoom:
![screen shot 2016-08-09 at 5 56 41 pm](https://cloud.githubusercontent.com/assets/7155109/17538528/23d5e232-5e5b-11e6-9ce0-9005b65de898.png)

I think the underlying problem is that **alignment packing uses genome coordinates (basepairs) not pixels**.  In `AlignmentPacker.java`, the `MIN_ALIGNMENT_SPACING` constant is set to 5bp.  When zoomed out, 5bp can be 0px.  Perhaps the packer should use 5px instead of 5bp, and packing should be re-triggered when the zoom level changes.

**Comment by jrobinso** [comment]
Keeping constant 5 pixel whitespace at low zoom might be problematic as packing would require more and more rows as you zoom out,  increasing apparent depth and causing alignments to jump about between rows.  Also, as you continue zooming out most of the view would eventually be taken by whitespace as alignments continue to shrink in size.   The problem here is the arrow at the end of the alignment is being drawn over the start/end of an adjacent alignment.  The alignment coordinates themselves will not overlap.   Perhaps this strand indicator (the arrowhead) could be phased out as you zoom out?  Alternatively it could be retained buy kept within bounds of the alignment rectangle, rather than appended to the end.

**Comment by amwenger** [comment]
> Keeping constant 5 pixel whitespace at low zoom might be problematic as packing would require more and more rows as you zoom out, increasing apparent depth and causing alignments to jump about between rows. Also, as you continue zooming out most of the view would eventually be taken by whitespace as alignments continue to shrink in size.

Excellent points, particularly about the 5px spacing being silly when the alignments themselves are 1px wide.  The scale at which that becomes a problem is quite different for long (10kb) and short (200bp) reads, but your proposal to remove/reduce the strand indicator arrow so that it does not draw over the adjacent alignments is probably the best pan-platform solution.  Read strand is not critical at the low zoom.

It would be nice to always maintain at least 1px between adjacent reads even if that means that half of the screen is whitespace.  Otherwise, it becomes difficult to tell when reads are separate and when they blend together.  Adjacent short reads begin to look like continuous long reads at low zoom, which could lead to incorrect inferences of variants from different reads being from the same haplotype.
