### ISSUE TITLE
Add progress dialog for loading CRAM alignments

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#311]
Loading CRAM alignments can take a very long time, due (I assume) to the need to load the entire chromosome/contig sequence into memory.  We need a progress dialog with information on what is going on.   Currently the app can appear frozen.

**Comment by jpaul6** [comment]
Related to this. Is this loading of the entire chromosome/contig sequence a feature of htsjdk? It seems very unfortunate.

**Comment by jrobinso** [comment]
Yes,  the htsjdk requires the entire sequence to decode any part of the
CRAM.  I agree its unfortunate.

**Comment by jpaul6** [comment]
I've looked through htsjdk code, and I think this limitation is somewhat artificial. I'm going to attempt to modify htsjdk so that a) the CRAMReferenceSource has a function for providing bases in a range, allowing the implementing class to decide on a fetching/caching scheme, and b) an option to turn off the MD5 checks, since these are computed for slices, and frequently cover large genomic chunks in sparsely populated regions (i.e. they'd require a large fetch). If we can fetch/cache a few thousand bases at a time, i believe performance will be improved by 4-5 orders of magnitude.

**Comment by jrobinso** [comment]
Well, first this would be a pull request for htsjdk, and you should open an
issue for discussion there first before investing a lot of time.   Turning
off MD5 checks is a bad idea, IMHO, and is not something I would support in
IGV without making you jump though a hoop or two  (probably by manually
editing the prefs file).  Without them you can load a CRAM against any
reference, and it looks just fine and dandy with no indication anything is
wrong.

**Comment by jpaul6** [comment]
Yeah, I'm going to do a little proof of concept before I start seriously considering a PR on htsjdk. I am in contact with some of the dev team, though. Regarding the MD5 stuff: that makes plenty of sense to me. The domain in which I'm working is programmatically loading IGV, so it's straightforward to examine the CRAM header and select the appropriate genome. Alternatively, I suppose, one could consider making CRAM slices that are bounded by genomic size as well as number of records, though compression would likely suffer a bit.

**Comment by jrobinso** [comment]
I think this is worth doing.   I started down this path myself, thinking it
would take a day or two,  and just found myself in a bit of a rathole of
unexpected places that depended on having the entire sequence (in the
htsjdk that is).
