### ISSUE TITLE
Read Loading is Extremely Slow When Large Splices are Present

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#319]
I used mapping parameters allowing reads to map across 100 million bases and opening the BAM file in IGV takes many minutes, as does changing the genomic view. This problem persists in the development version of the software. A simple example is:
- Download the ZIP file with BAM and BAI files in it.
- Use `File` -> `Load from Server...` to open the BAM file.
- Type PDCD4 into the search tool and click on it to go there.
-  Right-click on the reads track and click on `Remove Track`. It will also be painfully slow.

[slowExample.zip](https://github.com/igvteam/igv/files/492064/slowExample.zip)

**Comment by jrobinso** [comment]
I can confirm that this is slooooooooow.    Thanks for the example,  looking into it.

**Comment by jrobinso** [comment]
Try the following experiment,  add this line to your prefs.properties file.  Be sure IGV is shutdown first, otherwise it will be overwritten

SAM.REDUCED_MEMORY_MODE=true

In this mode IGV does not retain read sequence information, nor does it load reference sequence to compare bases for snps.  It treats alignments basically like bed records.    I'm not proposing this as the solution,  but based on this experiment the culprit seems to be sequence.

**Comment by jrobinso** [comment]
This is what I see in reduced memory mode,  alignments that span the entire chromosome.   This is definitely not a case I designed for,  and will require some thought.   Perhaps "reduced memory mode" or something like it is the solution for alignments like these.

**Comment by DarioS** [comment]
Even with the reduced memory setting, IGV struggles in regions with a concentration of reads (e.g 100 reads in an exon). For example, type chr10 100003848 once the example BAM file is loaded and it freezes for a few minutes. This suggests that the cause is something other than the sequence information.

Many of the split reads look dubious and could be removed with better mapping parameters, but I found a location that has convincing splices, so I think IGV should handle this case in version 3.

**Comment by jrobinso** [comment]
Running the development version I can't provoke any performance problem at that locus, or any other,  with reduced memory on.   Are you sure its on?   Check your prefs.properties file.

This is an interesting example bam, but it is also an outlier of sorts.    IGV is not designed for 100 MB alignments.  A multiple alignment or assembly viewer might work better.    Having said that  I can't reproduce your errors with "reduced memory" mode on.

**Comment by DarioS** [comment]
Indeed, it works better on the snapshot version. I was using 2.3.81 earlier today. Could it be made more efficient so that reduced memory mode is not necessary?

**Comment by jrobinso** [comment]
For 100MB alignments? Doubtful, or would require a lot of work.    IGV
might not be your tool for this.   Sequence and base level coverage are the
main culprits here, I suspect, both of which are sacrificed for "reduced
memory".

Could you list here what information you loose in "reduced memory" that you
would want to see at these scales?  SNPs can obviously not be seen, what
else?   It will be useful as this support for wide genomic range is
refined.

This is not a priority, to be honest,  but its interesting to pursue these
outlier cases as they expose flaws not seen otherwise.

**Comment by jrobinso** [comment]
One other suggestion, if the 100MB split reads are dubious filter them out.  These are the main culprit here I'm fairly certain.   As an experiment try filtering all alignments whose reference span is > 10MB and see how it behaves.

**Comment by DarioS** [comment]
> ... what information you loose in "reduced memory" that you would want to see at these scales?

None, but it would be convenient to be able to switch between different scales without having to restart IGV and change the properties file.

> This is not a priority ...

That's understandable.

**Comment by jrobinso** [comment]
Oh yea, the intent is to make the switching easy and in fact possibly
transparent.  That is to say,  when zoomed out sufficiently far it might
switch to "reduced mode" automatically, and vice versa.

In the meantime,  filtering out the 100MB alignments which most likely are
artifacts should improve performance.
