### ISSUE TITLE
Cannot open/download IGV browser

### ISSUE THREAD

**Issue by smolgoan** [igvteam/igv#325]
A number of users reported the issue: previously installed igv.bat failed to open a browser. The error message stated : Range-bytes test failed.

When trying to open the browser from Broad website using 'Launch' button they got error message 'Failed to open application'. 

We investigating the failure with our networking team, but also would like to learn your opinion: is it possible that infrastructure changes at Broad Institute prevent us from using IGV? Anything that we should be aware of?..

Many thanks

**Comment by jrobinso** [comment]
This is not likely an internal Broad issue as I can access and use the browser from outside the Broad.  Its more likely a change in your internal network environment.  Have you added a proxy or firewall, or changed configurations on an existing proxy or firewall?   Range-byte tests sometimes fail because a proxy removes "Range" headers from the client (IGV's) http request.  

It would help to have more details on the errors, they don't really make sense as reported.  Could you provide more details and screenshots,  also "igv.log" files which you can find in an "igv" folder under the user's home directory.    WRT the "Launch" button error, a dialog is presented with options for more details.

**Comment by smolgoan** [comment]
[CK_igv.txt](https://github.com/igvteam/igv/files/534900/CK_igv.txt)
Thank you very much for your response! yes, more than likely the issue resides on our site. Just in case I attached log file.

**Comment by jrobinso** [comment]
Actually this might be a problem at our Amazon hosting site.  I have made
an update to the hg19.genome file that might resolve it.  Could you try the
following on one of the client machines?

(1) clear the genome cache by deleting or moving all file from the folder
 <user home>/igv/genomes.   Alternative you can just delete hg19.genome.
This folder is just a cache
(2) restart IGV and load hg19.genome again from the server (Genomes > Load
from server...)
(3) see if the problem is resolved.

If this does not resolve the problem  please send the log file again.  It
would be helpful if you delete or move the current igv.log file before
restarting IGV.

Apologies and thanks for your patience.

**Comment by jrobinso** [comment]
After further investigation I think an IGV update will be required.  Please download and try 2.3.83 and reply here with the result.

**Comment by smolgoan** [comment]
Thank you, Jim!
