### ISSUE TITLE
hg38 genome not what's expected

### ISSUE THREAD

**Issue by alizrrao** [igvteam/igv#363]
The hg38 genome seems to be incorrect in every region I look at. E.g. according to UCSC genome browser, hg38 chr1:1935119- and onward should be TTGTAGGTAGGTAC... and this sequence is true for my sequenced samples when looking in IGV. But IGV shows mismatches to the reference in nearly every position (see attached screenshot). I had added hg38 from the IGV server.

The same problem happens using IGV_2.0.34 and IGV_2.3.26. Additionally, the RefSeq genes feature track does not appear in IGV_2.3.26. I'm using a machine with CentOS release 6.2.

Thanks ahead for any advice on how to fix these issues.

![image](https://cloud.githubusercontent.com/assets/1855143/22274372/0615695a-e25b-11e6-9e8d-a86803893294.png)

**Comment by jrobinso** [comment]
Hi,  I don't see the IGV sequence track.   I suspect you have a network
issue,  possibly a firewall that is removing range-byte headers from
outgoing requests (i.e. requests from IGV to our server),  but can't be
sure.   I've attached what I see, which is the correct sequence.

To solve this you could download the fasta locally to use as a reference.
Also,  I would suggest you update your copies of IGV,  those versions are
well out of date.   With the latest version you can download the fasta
sequence when you download the ".genome" file.

**Comment by AMChalkie** [comment]
We've had similar issues with the genome track downloading but then getting
"the rainbow art project" alignment, in spite of a hg19.genome being
downloaded. Is it worth adding a md5 checksum or similar to verify that the
downloaded file is correct? As I consider an incorrect .genome file should
be a fatal error, particularly for those new to looking at IGV.

**Comment by jrobinso** [comment]
There is no problem with the .genome file,  it would pass and MD5 check,
and it in fact contains no sequence.    When this problem occurs it is
usually because a proxy or firewall removes "Range byte" headers on
outgoing requests (IGV -> server) for specific slices of sequence,  so the
server streams back sequence from position 0 instead of what is requested.
  The latest versions of IGV have checks for this and re-do the requests
using a server we host and parameters for the sequence requested.   The
original poster is using IGV versions several years old.

An MD5Sum check is interesting but what would it be computed on?   Sequence
is requested in small random chunks depending on what you have in view.

If you are in an organization that deploys such proxies and are not able to
get the configuration changed the best solution is to download fastas
locally.    We host these files as a service and they work for the vast
majority of people,  for others local fastas are the recommended solution.

**Comment by alizrrao** [comment]
Thank you for your suggestions, I believe the problem may have indeed been the proxies or firewalls, as I'm getting the following errors when I first run IGV:

GConf Error: Failed to contact configuration server; some possible causes are that you need to enable TCP/IP networking for ORBit, or you have stale NFS locks due to a system crash. See http://projects.gnome.org/gconf/ for information. (Details -  1: Failed to get connection to session: /bin/dbus-launch terminated abnormally without any error message)downloading the FASTA file solved the problem. In case anyone else has this problem: Because I had already attempted to add hg38 to my genomes list, hg38 was no longer appearing in the list of genomes on the server, and I wasn't able to select the box to download the FASTA sequence from within IGV. Therefore I installed IGV on a different machine, downloaded the FASTA file there, and copied it to the igv/genomes directory on the machine in question.

**Comment by jrobinso** [comment]
Thanks for the update.   I will try to do something about the confusing menus,  an alternative to your procedure is to "Manage Genomes.."  and remove hg38,  then reload it.  This is not at all obvious though.
