### ISSUE TITLE
Save image as .svg/.eps simplification

### ISSUE THREAD

**Issue by Mashin6** [igvteam/igv#373]
Currently when I open IGV exported .svg/.eps files in Illustrator, I always spend 10+ minutes deleting unwanted backgrounds, lines, groups, clipping masks, etc. to obtain usable figure.

I wonder if it would be possible to somehow simplify exported pictures or add options to the export dialog window that would allow only certain objects to be exported.

**Comment by jrobinso** [comment]
You can right-click on a panel and save just the panel, rather than the
whole screen.   Have you tried that?

I'm aware of the problem,  and hope to improve on this in the 3.0 release.

**Comment by Mashin6** [comment]
Thanks for pointing that out. It definitely reduces the workload a bit, but it still would be nice to not have to delete scrollbars and other stuff every time.

**Comment by jrobinso** [comment]
Another alternative is to use a batch script.   Its a little clumsy but
creates offline images avoiding the windowing system.   Save the following
to a file and edit the "snapshotDirectory".   Then from the Tools menu
select "Run batch script".

snapshotDirectory /Users/jrobinso
maxPanelHeight 600
snapshot test.svg

**Comment by holgerbrandl** [comment]
And  don't miss https://gist.github.com/dfjenkins3/5c6dc1e55e78fa17b931 which details out how to use `bedtools igv` to prepare a batch script.

**Comment by youngjack86** [comment]
Hi all,
I'd like to add my comments to this issue. Since the IGV generated SVG file usually contains lots of SVG styles with duplicated descriptions and this may further make the SVG file more complicated and then downstream software slow to parse it. Beside restrict the output region and decrease the output reads number, maybe the best way to minimize the SVG file size is to merge the features with exactly the same style.
Could this be done in the later updates of IGV? Many thanks.

**Comment by jrobinso** [comment]
@youngjack86 I would welcome a pull request for this.    I think igv.js does a much better job with SVG output, but isn't batch runnable as of now.   However personally I am more likely to invest time on that as a long term solution.   Only so many hours in a day.
