### ISSUE TITLE
Allow resetting prefers by loading a properties file

### ISSUE THREAD

**Issue by fleharty** [igvteam/igv#406]
Often times I find myself in a situation where I'm using IGV for a particular type of analysis, say germ line variants, and then I switch to examining somatic variants, or even structural events.

It would be cool if there were a way to load/save settings (in the preferences menu) based on what I'll be working on.

Is this a feature other people would be interested in?

**Comment by jrobinso** [comment]
That would be nice,  "export and import" preferences?    Until we can
implement this there is a way to do it manually.   Make a copies of the
"prefs.properties" file in the igv folder,  one for each set you want to
restore.   Then copy this set back to "prefs.properties" before starting
IGV.   It won't work to do it while IGV is running.   I recognize this is a
bit of a pain,  but is the best we can do right now.

Will definitely implement this,  I'm surprised it hasn't been requested or
occurred to us before.

**Comment by fleharty** [comment]
@jrobinso Awesome!  Thanks Jim.

I don't really have preferences, but it sounds like you could have different versions of "prefs.properties", and just load the one you want.

Your suggestion, though a bit of a pain is actually not a horrible solution.

**Comment by jrobinso** [comment]
@fleharty 2 years later and still not implemented.  This turns out to be a complex case to support as we would need to expose prefs.properties in a way we didn't design for.  However since this was posted we have refined preferences for alignments to be sequence platform dependent, with separate groups for dna, rna, and 3rd gen (pacbio) sequencing.   The type of experiment is determined by the reads themselves.    This should get at the problem of needing to switch preferences for different experiment types, does that satisfy your needs?

**Comment by fleharty** [comment]
@jrobinso 
This may satisfy my needs.  I will experiment with the new feature.  If I find that's not sufficient I can reopen this ticket.
