### ISSUE TITLE
Changing SHA checksums of releases

### ISSUE THREAD

**Issue by sambrightman** [igvteam/igv#413]
See e.g. homebrew/homebrew-science#5706 and homebrew/homebrew-science#5622 (described as the "beginning of a pattern" due to homebrew/homebrew-science#4378). It looks like releases are being made and later changed, or the releases are compromised. There are seemingly no SHA checksums available on the download page to verify.

**Comment by jrobinso** [comment]
Hi, 2.3.93 has not been released yet,  until I update the links on the downloads page it is just a candidate.  How did you get a link to this?    I'm not familiar with homebrew-science.

**Comment by sambrightman** [comment]
I assume that people get it from the Github releases page - there is already a v2.3.93 tag and zip file at the same download location. It would be more usual not to tag a release until the release is made, and use e.g. `-rc1` or `-beta1`-style tags for candidates, as this makes things clearer for everyone.

Would it be possible to verify the SHA256 checksum of the v2.3.92 ZIP? Do you think checksums could be published on the downloads page?

**Comment by jrobinso** [comment]
Hi,  I didn't know Github did that.  How does it determine a release?
 The official release is on our webpage, not github,  sorry for the
confusion.   I will see if I can disable creation of the referenced zip.

**Comment by sambrightman** [comment]
It would be much clearer to only create the release tag when there is a release, TBH. Any way to confirm checksums?

**Comment by ilovezfs** [comment]
In future: please don't retag Git-based projects for a few reasons:
- when you retag you break the from-source build for anyone using Homebrew (and also possibly other projects)
- when you retag we don't know until a PR is filed whether it was intentional or you've been hacked
- we (and you) now can't easily differentiate between users using the old tag or the new one as they have the same Homebrew version number
- when you retag anyone who has done `git fetch --tags` and runs it again will not receive an updated tag. This is because Git is designed to not update tags as they are meant to be permanent. Retagging in Git-land is equivalent to force-pushing to a public branch (i.e. bad)

As a result of all this the ideal thing to do in this case is a `2.3.92.1` release. Thanks!

Note that GitHub also lets you explicitly mark the latest release version to differentiate from mere tags, as well as upload specific release tarballs as needed.

**Comment by jrobinso** [comment]
OK, thanks for the input.
