### ISSUE TITLE
Visualize orientation in bed-tracks

### ISSUE THREAD

**Issue by holgerbrandl** [igvteam/igv#461]
It seems that just alignment (bam/sam) and gff tracks support strand-visualization (when using igv viewer v2.98). It would be great such a feature could be added for bed-tracks as well. 

E.g. when using 6 column bed input such as 
```
chrI	335	649	YAL069W	.	+
chrI	538	792	YAL068W-A	.	+
chrI	1807	2169	YAL068C	.	-
```
it would be great if forward loci could be highlighted differently from the reverse strand loci.

I've tried https://software.broadinstitute.org/software/igv/TrackLine to see if there would be a trackline option to enable it, and also have checked the corresponding format https://software.broadinstitute.org/software/igv/BED but neither gave a hint.

**Comment by jrobinso** [comment]
This is a bug,  not a missing feature,  I'm looking into it.

**Comment by jrobinso** [comment]
OK, the problem here is the use of "." for score.  When IGV encounters a token it doesn't understand it ceases trying to parse the bed line.   This allows it to load a lot of "bed like" files that aren't really UCSC bed files.   The use of "." here is probably legal,  there isn't really a spec for BED or anything else at UCSC, but currently IGV chokes on it.   I'll modify the parser to allow "." and interpret it as 1000,  if userScore is not on in the track line this value is not used.    This change should be in the nightly build,  and in the next 2.4 point release.

**Comment by holgerbrandl** [comment]
Awesome, thanks for the great support.
