### ISSUE TITLE
chromosome scale visualisation gives unwanted read-count display

### ISSUE THREAD

**Issue by chrisclarkson** [igvteam/igv#479]
Hi I really like the output that IGV gives me on a genome wide scale (see attached png):

![screen shot 2017-10-26 at 10 06 58](https://user-images.githubusercontent.com/26774207/32044469-8a7aa41e-ba35-11e7-9d92-683f484585a9.png)

But when I go to a single chromosome scale it gives an unwanted format- **the histogram format has disappeared** (while the colours are different the data is the same):

![screen shot 2017-10-26 at 10 07 30](https://user-images.githubusercontent.com/26774207/32044593-e6f13f46-ba35-11e7-8a75-f7980e415aec.png)

Is there any way that I can change it back to the format that it was at while on a genome-wide scale- except on a single chromosome level...?

**Comment by jrobinso** [comment]
If you want a histogram you need to use a bedgraph or wig format.   The files you are displaying are feature files.  The whole genome view shows the density of features because in general you there is not room to show individual features.

So the short answer is no.   Long answer is that if you want to view the density of features you need to compute that and use an appropriate format.
