### ISSUE TITLE
Add option to disable transparency for overlaid tracks

### ISSUE THREAD

**Issue by Mashin6** [igvteam/igv#480]
I am trying to overlay 10 bedgraph tracks of non-overlapping data, but running into some issues. Would it be possible to implement:

1) Continuous autoscaling when panning the data. When I group autoscale the Overlay track, IGV currently autoscales permanently to the highest value in the dataset not in the given window. 
(Although, for some tracks it seems to be working fine and for some not.)

2) Have an option to turn off data transparency for Overlay tracks. Transparency is useful if data points are overlapping, but in my case is just decreases visibility.

<img width="1374" alt="screen shot 2017-10-30 at 7 46 25" src="https://user-images.githubusercontent.com/5265707/32201065-39f49076-bdab-11e7-9d7d-7437db67726e.png">

**Comment by jrobinso** [comment]
Hi, the autoscaling problem should be fixed with the latest commit to master.  There was another bug in the treatment of merged tracks.   Specifically, autoscaling a merged track should be equivalent to group autoscaling the individual tracks.   Nothing else makes sense.   This was not treated correctly but has been fixed.

Yes it would be reasonable to turn off transparency,  we'll add this as an option.
