### ISSUE TITLE
Junction values in Sashimi plots increase when settings are changed

### ISSUE THREAD

**Issue by guillaumecharbonnier** [igvteam/igv#510]
![image](https://user-images.githubusercontent.com/20519429/35155681-bc085a1c-fd2e-11e7-80f2-c922ed60b46f.png)

Changing "combine strands" to "forward strands" then "combine strands" again:
![image](https://user-images.githubusercontent.com/20519429/35155743-f947294e-fd2e-11e7-9efc-166f68b52fb4.png)

It is also happening when changing "Set junction coverage min". 

I am using IGV v2.4.3. Same issue with v2.4.6.

**Comment by jrobinso** [comment]
I am not able to reproduce this.   Can you reproduce the problem with the attached session  (unzip the session file, the load from  "File > Open Session...")?
[sashimi_test.xml.zip](https://github.com/igvteam/igv/files/1648356/sashimi_test.xml.zip)

**Comment by guillaumecharbonnier** [comment]
I am not reproducing the issue with your session. Here is one small example:
[igv_session_sashimi_bug_junction_values.zip](https://github.com/igvteam/igv/files/1648781/igv_session_sashimi_bug_junction_values.zip)
The issue also happen with the whole genome bam produced by STAR.

**Comment by jrobinso** [comment]
OK, thanks for the test case.    This was a real bug,  its surprising it hasn't been noticed before.  I think the reason is you would only notice this if there were a substantial number of reads on both strands at a locus.    This does not usually occur with stranded RNA seq experiments, for which the sashimi plot is commonly used.   It looks like your dataset is non-stranded.
