### ISSUE TITLE
[SUCCESS] Running IGV on Mac OS X 10.13 with Java 10 still installed

### ISSUE THREAD

**Issue by alexgraehl** [igvteam/igv#544]
Hi,

 I've only seen people indicating that they can't run IGV due to the system version of their Java being Java 10.

 I was under the incorrect impression that IGV could NOT be run on a Mac system with Java 10 on it, but it turns out that it's relatively easy to use Homebrew to install Java 8 and run IGV via Java 8 while keeping Java 10 as your system version of java.

Someone wrote up GREAT instructions for generic Java version selection here: http://davidcai.github.io/blog/posts/install-multiple-jdk-on-mac/

Here's what I did on the Mac under 10.13 (High Sierra) to make things work:
* `brew tap caskroom/versions`
* `brew cask install java8`
* `brew install jenv`
* `mkdir -p ~/.jenv/versions`
* `jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/`
* `jenv versions`
* `cd /Applications/IGV_2.4.10.app/`
* `jenv local oracle64-1.8.0.131`
* I then totally failed to figure out how to use jenv successfully, but was able to directly run the IGV.jar using Java 8 with this command:
* `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java -jar /Applications/IGV_2.4.10.app/Contents/Java/igv.jar`

And the result is that IGV runs perfectly on Mac OS 10.13 with Java 10 still installed.

There's probably a more elegant way to do that above; my "jenv" install ended up being a dead end, as I couldn't figure out how it worked.

It would be great if this process could be documented somewhere semi-official, as the only Internet results I could get were of people who couldn't get IGV to work.

**Comment by jrobinso** [comment]
Thanks for the information!  I didn't know this was possible.

**Comment by weshorton** [comment]
Thank you!!

I added the following in my `.bashrc` to make it easy to run:

```
### Will run from command-line, but requires open terminal
### Usage: `~$ IGV`
alias IGV="/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre/bin/java -jar /Applications/IGV_2.4.10.app/Contents/Jav\
a/igv.jar"

### Open detached screen and then run from there
### Usage: `~$ igv`
### Recover screen: `screen -S igv -r`
### Kill screen: `screen -X -S igv quit`
function igv ()
{
    # detached screen called "igv"
    screen -d -m -S igv
    # Run IGV command inside "igv" screen
    screen -S igv -X -p 0 stuff $'IGV\n'
}
```

I found [this](https://stackoverflow.com/questions/28774681/run-commands-in-screen-after-creating-one-per-bash) helpful post for how to send commands to a detached screen.

**Comment by wyattmcdonnell** [comment]
Thanks a million for this @alexgraehl and @weshorton!

**Comment by davideby** [comment]
Hi all,

Though this is not mentioned anywhere on our site yet, there is now a Java 10 compatible Snapshot build in the [Archived Downloads](http://data.broadinstitute.org/igv/projects/downloads/snapshot_java10/) area.  It's available as our usual Binary distribution and also as a Mac.app (though unsigned for now, due to issues with our signing server).

Like all Snapshots, it's not yet considered fully Production-ready.  It has been tested and seems to work fine, but it's quite possible there could be hidden issues especially because of the large changes since Java 8.  Definitely post new issues for us if you find any problems.

While Java 9 is considered EOL, if you're still using that this build ought to work with it as well.  It is *not* compatible with the Java 11 Early Access builds; we'll have to do another release later for that.

Thanks,
David

**Comment by davideby** [comment]
Just to follow up, after posting this yesterday we decided it's probably best just to pull the Mac.app build since it's unsigned.  We'll just distribute the usual Binary distribution for now.
