### ISSUE TITLE
Please add documentation how to build the project

### ISSUE THREAD

**Issue by yurivict** [igvteam/igv#555]
When I build the jar with Ant, the resulting jar doesn't include the jars in the libs/ folder.

gradle_readme.txt doesn't explain how to build a single jar that can be used to run the project.

Please look how Arch linux just installs 3 jars which are sufficient: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=igv

**Comment by davideby** [comment]
The documentation is here:
https://github.com/igvteam/igv/blob/master/gradle_readme.txt

ArchLinux doesn't "build" anything.  It downloads and unpacks a bundle from our website and expands that for delivery.

We have an additional build process behind the scenes that optimizes these JARs and signs them using a private certificate.  That's what produces the three JARs in our download bundle.

**Comment by yurivict** [comment]
```gradle_readme.txt``` doesn't even have an option to build a single jar. It creates a zip file with many jars. There should be an option to build a single jar if packagers would like to have just one jar without signing.

**Comment by davideby** [comment]
We can't do this as a single jar.  As you can see from that ArchLinux link you sent, there are at least three jars required because of the way some third-party libraries package their own components (goby & batik).

However, on thinking about this some more we're going to split out the jar optimizing pass - which *could* be public - from the signing, which must be private.  That would give you the three equivalent jars, just unsigned.

The Ant build-shrink.xml script handles this but we need to simplify it and document.

FYI, this is all going to be changing with Java 9 anyway, where Java modules are defined per-jar.  Better start thinking ahead about how to deal with that.
