### ISSUE TITLE
Support .json genome definitions with hidden "search" annotation file

### ISSUE THREAD

**Issue by finswimmer** [igvteam/igv#589]
Hello everyone,

annotation files become bigger and bigger. For example the annotation file for GRCh38 provided by ensembl has around 400MB if uncompressed.

When trying to load such big file igv suggested to compress and index this file. This works, but one cannot use the search bar to jump to a feature due to the compression.

When I now try to create a `.genome` file and reference the compressed and indexed annotation file, the loading of the annotation failed. I've found out, that neither the index file is packed into `.genome` file nor there is a reference to it in the settings file. In my opinion this is a bug that could/should be fixed.

As a feature request I suggest to implement a way to use the search bar for compressed and indexed file. For example if one create a `.genome` file igv could create an additional index for the feature names.

fin swimmer

**Comment by jrobinso** [comment]
Hi,  its not possible to search on compressed files since that would require loading the entire file,  which would defeat the purpose of compressing and indexing it.   You can create an "additional index" easily by grepping out the feature records you want to search on and load them as a plain gtf or bed file from the file menu.   In GTF files this is often the "gene" or "transcript" records.    This can be loaded from the file menu.   Alternatively, the smaller file could be used as default annotation in the .genome file and the full, compressed indexed gtf loaded separately as a file menu.

Secondly,  you can't use compressed annotation files in the ".genome" file.

In development we have a json format as an alternate to the .genome file,  and with it you can reference compressed index annotation files (not just 1, but as many as you want).   This format is used for igv.js.   With that format you could load a smaller uncompressed file with the search terms you want to include,  and the full indexed file.   Until this is released, which won't be long,  you can accomplish the same thing using the file menu.

**Comment by jrobinso** [comment]
See https://github.com/igvteam/igv.js/wiki/Reference-Genome-2.0 for a description of the json format (the doc uses js objects, but json equivalent can also be used).   One of the track attributes is "searchable",  so you could load a small track for searching and the compressed gtf.    Alternatively, and not mutually exclusive,  we could add a property that loads an annotation file strictly for searching purposes and does not produce a visual track.    I think that would fulfill your requirements.

**Comment by finswimmer** [comment]
Hello @jrobinso ,

thanks a lot for your detailed answer. What is in development sounds very promising.

> we could add a property that loads an annotation file strictly for searching purposes and does not produce a visual track.

Indeed this would perfectly fulfill my requirements.

fin swimmer

**Comment by jrobinso** [comment]
At long last this is supported, an example json genome definition follows.   This has actually been implemented for a number of releases, but will be officially supported in the upcoming 2.11.0 release


```json
{
  "id": "hg19",
  "name": "Human (CRCh37/hg19)",
  "fastaURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta",
  "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta.fai",
  "cytobandURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/cytoBand.txt",
  "aliasURL": "https://s3.amazonaws.com/igv.org.genomes/hg19/hg19_alias.tab",
  "tracks": [
    {
      "name": "Refseq Genes",
      "format": "refgene",
      "url": "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeq.txt.gz",
    },
    {
      "format": "gtf",
      "url": "https://s3.amazonaws.com/igv.org.genomes/hg19/gencode.v24.genes.gtf.gz",
      "hidden": true
    }
  ]
}
```
