### ISSUE TITLE
Missing Quality Displayed as -10

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#628]
For A VCF file which has the QUAL column with missing values, represented by a dot as the VCF specification allows, hovering over the SNP shows a Qual value of -10. By definition, valid QUAL values range from 0 to infinity, because the input value is a probability and probabilities have to be between 0 and 1, so this is confusing to a new user like me.

```r
> -10 * log10(1)
0
> -10 * log10(0)
Inf
```

Can IGV please represent missingness differently?

**Comment by jrobinso** [comment]
This is difficult because we report whatever the htsjdk tells us.  There have been various conventions for specifying missing values in vcf,  the dot, -1, and -1.0,  but I've never seen -10.

Could you attach a small vcf (you'll need to zip it) with this problem,  I'll load it and step through the htsjdk to see where -10 is coming from.

**Comment by DarioS** [comment]
The test VCF is attached. Any SNP will show as -10 in IGV. It's in reference to hg38.

[primaryTissue.somatic.snvs.candidates.vcf.gz](https://github.com/igvteam/igv/files/3715958/primaryTissue.somatic.snvs.candidates.vcf.gz) (91 KB)
