### ISSUE TITLE
Enable mutation colors in MUT/MAF files

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv#687]
The UI for changing the colors used for mutations in MUT/MAF files is now in View > Color Legends. It used to be in View > Preferences. However, the checkmark for enabling/disabling the use of colors is gone, and it is always disabled. We should just make them always enabled. No need for a checkmark.

**Comment by jrobinso** [comment]
Actually there's a reason for that flag.  Without it you get colors for all the types, even if you didn't set or want any colors there are default colors.   Since removing the flag and coloring whether you want it or not would be a radical change to current behavior I think we should just add the flag to the preferences UI.
