### ISSUE TITLE
add an option to generate session file with relative paths

### ISSUE THREAD

**Issue by libor-m** [igvteam/igv#69]
Loading of 'relative' sessions already works, it would be nice if IGV was able to generate those relative sessions as well. 

One way how to do this is to remove the path to the session file from all other paths in that file. The result would be a project that is self contained in given folder, and transferable to other machines.

**Comment by jrobinso** [comment]
This is an old thread, but I thought it should be updated since session behavior is changing with the next release.  Relative path generation is available but you must enable it via the preferences window.   Select View > Preferences > General >  "use relative paths in sessions".    This is not at all straightforward, and computation of relative paths is known to fail for certain OS / Java combinations on symbolic links,  thus it will be off by default.

**Comment by libor-m** [comment]
Thanks for the notice.

**Comment by duartemolha** [comment]
Sorry to come back to this but I have the option for relative paths checked and the sessions file created still do not have relative paths

**Comment by gorgitko** [comment]
@duartemolha I can confirm this on IGV 2.9.2 on Linux.
