### ISSUE TITLE
Detection of experiment type (alignments)

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv#732]
Experiment type (DNA, RNA, 3rd Gen)  for alignment tracks is determined from the reads themselves.   The type determines the default preference for the track, such as visibility window.     This does not happen until you zoom in to trigger a load, so initially all tracks have the default "DNA" preference set.   Should we read enough alignments when the file is initially loaded, prior to zooming in, to determine type?

**Comment by amwenger** [comment]
I like the idea of peeking at the first few alignments.  Even if the first regions of the genome are not representative, the length of the aligned reads (including the clipping) should still be identifiable.

Two other options to identify PacBio reads from metadata rather than alignments:
* `PL:PACBIO` in the read group header lines, when available
* read names follow the convention `m<INSTRUMENT_NUMBER>_<YYMMDD>_<HHMMSS>/<...>`, for example, `m54334_180924_221206`.  Of course, NCBI SRA renames reads using its own convention; so, this does not hold for PacBio data downloaded from SRA.
