### ISSUE TITLE
Newest versions of IGV are no longer on data.broadinstitute.org

### ISSUE THREAD

**Issue by dinvlad** [igvteam/igv#773]
Hi Team,

Our builds that download the latest version of IGV from `data.broadinstitute.org`, are now broken, since the latest versions (`2.8.1`, `2.8.2-rc1`) have not been uploaded to https://data.broadinstitute.org/igv/projects/downloads/2.8.

Would it be possible to upload them?

Thanks

**Comment by dinvlad** [comment]
Thanks for uploading `2.8.2-rc2`. My only complaint is that it has a lower-case `igv-` prefix instead of the expected `IGV-`. Would it be possible to use either prefix for all builds?

**Comment by dinvlad** [comment]
Also, on GH there's no release called `2.8.2-rc2`. This is also breaking our builds..

**Comment by jrobinso** [comment]
Hi, obviously don't know your process, but I think you are going to have to change your build process to not be dependent on our tags or the internal structure of our broad directory structure.

**Comment by jrobinso** [comment]
If you want to discuss via broad internal email please send me a message there.

**Comment by dinvlad** [comment]
Thanks - I just wanted to make sure we can always install the latest version. So far, we relied on GitHub tags to determine the latest version, and then download it from the broad directory, since GitHub doesn't host pre-built binaries for this repo. I'd be awesome of they were hosted here though.

Alternatively, we have to build IGV from source every time, or rely on manual updates to the version tag, to be downloaded from Broad..

**Comment by jrobinso** [comment]
Why don't you just download our binaries when we release them?  There is
always a delay between a git tag and artifacts appearing on the downloads
folder, it is a manual process and sometimes takes days or longer since the
Mac artifacts have to be manually signed by a team member who lives in
Japan.

I'm also curious about your comment wrt the tag "2.8.2-rc2".   Where did
you get that tag?   That has never been pushed to github.

I'm not sure this is the best forum to discuss internal Broad processes,
perhaps we should continue this by email,  or you can meet personally with
Helga who probably sits close to you.

Jim

**Comment by dinvlad** [comment]
Ok, thanks. I think we're covered for now.
