### ISSUE TITLE
IGV not running

### ISSUE THREAD

**Issue by aude-darracq** [igvteam/igv#789]
Hello,
 
I have installed igv 2.8.2 on a linux server (updated with java 11), but when I want to launch it with igv.sh, I got a full yellow window with nothing else inside (no menu bar, no genome, ...).

Do you have any clue to help me ?

Here the output of IGV

> Using system JDK.
> WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
> WARNING: package sun.awt.windows not in java.desktop
> openjdk version "11.0.6" 2020-01-14 LTS
> OpenJDK Runtime Environment 18.9 (build 11.0.6+10-LTS)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10-LTS, mixed mode, sharing)
> WARN [2020-04-01T10:00:22,108]  [Globals.java:139] [main]  Development mode is enabled
> INFO [2020-04-01T10:00:22,135]  [DirectoryManager.java:179] [main]  IGV Directory: /home/user/igv
> INFO [2020-04-01T10:00:23,200]  [Main.java:159] [AWT-EventQueue-0]  Startup  IGV Version 2.8.2 03/23/2020 08:58 PM
> INFO [2020-04-01T10:00:23,216]  [Main.java:160] [AWT-EventQueue-0]  Java 11.0.6 (build 11.0.6+10-LTS) 2020-01-14
> INFO [2020-04-01T10:00:23,217]  [Main.java:163] [AWT-EventQueue-0]  Java Vendor: Oracle Corporation http://java.oracle.com/
> INFO [2020-04-01T10:00:23,217]  [Main.java:165] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM 18.9   
> INFO [2020-04-01T10:00:23,218]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory... 
> INFO [2020-04-01T10:00:23,287]  [Main.java:168] [AWT-EventQueue-0]  Default User Directory: /home/user
> INFO [2020-04-01T10:00:23,288]  [Main.java:169] [AWT-EventQueue-0]  OS: Linux 3.10.0-957.5.1.el7.x86_64 amd64
> INFO [2020-04-01T10:00:24,184]  [GenomeManager.java:192] [pool-3-thread-1]  Loading genome: /home/user/igv/genomes/hg19.genome
> INFO [2020-04-01T10:00:29,998]  [GenomeComboBox.java:90] [AWT-EventQueue-0]  Enter genome combo box
> INFO [2020-04-01T10:00:30,010]  [GenomeManager.java:284] [pool-3-thread-1]  Genome loaded.  id= hg19
> INFO [2020-04-01T10:00:30,018]  [CommandListener.java:120] [Thread-4]  Listening on port 60151

_

**Comment by davideby** [comment]
Hi,

It looks like this is the command-line bundle, correct?  We would recommend most GUI users to use the [dedicated Linux bundle](https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_Linux_2.8.2.zip) since it includes a known-working JRE (from AdoptOpenJDK), which simplifies support.  The command-line bundle is intended for more advanced uses, though obviously the GUI should still also work.

Quite a few Linux distributions default to installing a "headless" JRE that doesn't work for GUI applications, for example, and other JDKs may have different issues.   We can only test on a limited number of platform & JDK combinations.  

If you really need the command-line bundle, I would suggest first making sure that your installed JRE/JDK has full GUI support.

Another thing to watch out for on Linux is that some distributions have switched to Wayland-based desktop environments, while Java generally still requires X11 for Swing GUI applications.  Supposedly this can be made to work (via XWayland) but we haven't tested this since none of our developers are on such distributions.

Finally, since you mention this is on "a linux server", if you are trying to launch IGV *from a remote computer* then you need to install X11 on that client and set up end-to-end X forwarding.  That's beyond any support we can offer.  You should instead check with your local colleagues or IT staff.

In general we would recommend simply installing IGV directly on the client as it runs fine on quite mainstream hardware.

Regards,
David

**Comment by aude-darracq** [comment]
Hello David,

We have installed the dedicated bundle (wget http://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_2.8.2.zip).
We have tried to run this IGV version using the system JDK and also the packaged JDK. Always the same yellow window.
The remote server also has X11.

Regards,
Aude

[cid:image001.png@01D608C7.18803DA0]

**Comment by aude-darracq** [comment]
PS. We are running this on CentOS 7.

Best regards,

[cid:image001.png@01D608C7.8EEA9260]
Stijn​

Trappeniers
System Engineer
[cid:image002.png@01D608C7.8EEA9260]
SESVANDERHAVE Belgium
[cid:image003.png@01D608C7.8EEA9260]
+32 16 808 237<tel:+32%2016%20808%20237>
[cid:image004.png@01D608C7.8EEA9260]
+32 485 781 029<tel:+32%20485%20781%20029>
[cid:image005.png@01D608C7.8EEA9260]
www.sesvanderhave.com<http://www.sesvanderhave.com/>



From: Darracq, Aude <Aude.Darracq@sesvanderhave.com>
Sent: Thursday, April 2, 2020 8:17 AM
To: igvteam/igv <reply@reply.github.com>; igvteam/igv <igv@noreply.github.com>
Cc: Author <author@noreply.github.com>; Trappeniers, Stijn <Stijn.Trappeniers@sesvanderhave.com>
Subject: RE: [igvteam/igv] IGV not running (#789)

Hello David,

We have installed the dedicated bundle (wget http://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_2.8.2.zip<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdata.broadinstitute.org%2Figv%2Fprojects%2Fdownloads%2F2.8%2FIGV_2.8.2.zip&data=02%7C01%7CStijn.Trappeniers%40sesvanderhave.com%7Cebcc62c400094c9866dc08d7d6cd781a%7C67cb092f1bf64d9da40ce009ebac5603%7C0%7C0%7C637214050278145038&sdata=xN9hgtHp6ODCsAGh0dr4j3VToD0aGBJJ6vt7J6awG4c%3D&reserved=0>).
We have tried to run this IGV version using the system JDK and also the packaged JDK. Always the same yellow window.
The remote server also has X11.

Regards,
Aude

[cid:image006.png@01D608C7.8EEA9260]

**Comment by helgathorv** [comment]
Hi Aude,
Did you try the Linux-specific bundle that David suggested?http://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_Linux_2.8.2.zip

Helga

**Comment by davideby** [comment]
Hi @aude-darracq,

Since this is a client/server arrangement, have you contacted your local IT staff to set up X11 forwarding?  We can't give that kind of support as it depends on many different things specific to your environment and outside the control of IGV.

David

**Comment by jrobinso** [comment]
I would add that client / server setups, that is server and client on different machines,  are not recommended nor tested for by us.  The X11 traffic will severely degrade performance.     The recommended setup is to install IGV on the client machine.

**Comment by aude-darracq** [comment]
Hello,

After few tests we have detected that the issue was coming from the remote desktop used on the Windows machine to access IGV on the server. For your information, in our case, the color display depth should have been set on 24 instead of 16.
Nothing related to IGV itself. 
@jrobinso, for us, IGV on a server has always been working very well :)

Thanks a lot to the IGV team for all the developments/improvements through the years !

**Comment by aude-darracq** [comment]
> Hi Aude,
> Did you try the Linux-specific bundle that David suggested?http://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_Linux_2.8.2.zip
> Helga

yes
