### ISSUE TITLE
Is it possible to process multiple bams in parallel

### ISSUE THREAD

**Issue by SHuang-Broad** [igvteam/igv#795]
Hi,

I constantly load multiple tracks accessing BAMs stored in the cloud, and the window size is typically ~100bp to 1kbp.

So it would be nice for IGV to parse/decode the reads from these bams in parallel (e.g. 1 thread per bam), if this isn't already the case.

Thanks!
Steve

**Comment by jrobinso** [comment]
Good suggestion,  I'm honestly not sure what it does now.   IIRC there are
some tricky issues with the htsjdk if you try to do certain operations in
parallel, but reading from different bams should be safe.   In any event
I'll have to investigate.

**Comment by jrobinso** [comment]
Looks like there is a single-thread bottleneck.   Its fixable, will update here when there is something to test.

**Comment by SHuang-Broad** [comment]
Thanks Jim!
Do you need a test session? I can provide one if needed.

**Comment by jrobinso** [comment]
@SHuang-Broad no I don't need a test session.    I'm pulling @lbergelson into this for comment because there might be a larger issue.

IGV is loading data from each track sequentially due to a bug introduced for supporting "group autoscale".   That is fixable.   However I note in the code that alignment tracks are loaded sequentially irrespective of this bug.   This is done, IIRC, because there was a thread safety issue with the htsjdk.   @lbergelson do you know of any thread issues that would prevent loading multiple bam files in parallel (in different threads)?    I think this was a real issue in the past, but I could be mistaken, and in any event it might no longer be.

**Comment by jrobinso** [comment]
OK, a small update.  I think the thread safety issue with the htsjdk is only when trying to query 2 regions from the same SamReader asynchronously,  this should not effect the issue here which is reading independent BAM files.   So sorry to disturb you @lbergelson, no issues.

This is slightly more complex than it should be,  but stay tuned there will be a fix.

**Comment by lbergelson** [comment]
Hey, missed the first message.  I agree that there shouldn't be any issues using 2 independent readers on bams.  It's occurred to me though that there might be thread safety issues with CRAM if you're sharing a reference reader between them though.  You probably need to create independent reference readers for every cram if you're loading them in parallel, which is definitely wasteful.  We can look into making that thread safe though. 

 @cmnbroad Any thoughts on that?

**Comment by jrobinso** [comment]
@SHuang-Broad  The snapshot build should be loading in parallel now.  I have not tested it on private Google bucket bams.   When you have a chance could you give it a test?  You can download it here:  https://software.broadinstitute.org/software/igv/download_snapshot

**Comment by jrobinso** [comment]
@lbergelson IGV supplies its own implementation of reference reader, and its not shared between CRAM files.   It probably should be, this is inefficient,  I assume I just need to make sure the method  ```public byte[] getReferenceBases(SAMSequenceRecord record, boolean tryNameVariants)```  is thread safe.   In any event that would be an optimization, it is not shared at the moment.

**Comment by cmnbroad** [comment]
I _think_ dispatching separate readers to different threads would _probably_ be ok. Sharing a single reader across threads is definitely not (certainly not for CRAM).

Having said that, there are quite a few classes in htsjdk that set global state. SamReaderFactory, SamWriterFactory, and BlockGunzipper to name a few (i.e., anything named setDefault*); so you may have to be careful if IGV relies on any of those.

**Comment by jrobinso** [comment]
@cmnbroad Definitely no to a single CRAMFileReader across multiple threads,  however I think multiple readers could share a single CRAMReferenceSource, if its implementation was thread safe.

**Comment by cmnbroad** [comment]
Sounds right.

**Comment by jrobinso** [comment]
Parallel loading should work robustely now in release 2.8.4.   Apologies for the delay, I was all in on the grant writing.   I still need to do the CRAMReferenceSource optimization discussed above,  I'll leave this open for that.
