### ISSUE TITLE
Visualizing bam file mapped to transcriptome fasta file

### ISSUE THREAD

**Issue by qianxu05172019** [igvteam/igv#832]
Hi,

I mapped my reads to mm10 transcriptome fasta file. I sorted and indexed my bam file and place the trasncriptome.fa, .bam file and .bam.bai file in the same folder. I also checked the name of my trasncriptome.fa and bam file, the names ate the same. My problem now is that it gives an error says that:

Error loading E:\1to1DMSCopy\week6\IGV_view\UM.long.sorted.bam: An error occurred while accessing: E:\1to1DMSCopy\week6\IGV_view\UM.long.sorted.bam Error loading BAM file: htsjdk.samtools.SAMException: Sequence name 'ENSMUST00000167415.7|ENSMUSG00000086429.9|OTTMUSG00000034748.3|OTTMUST00000090750.1|Gt(ROSA)26Sor-204|Gt(ROSA)26Sor|551|antisense|' doesn't match regex: '[0-9A-Za-z!#$%&+./:;?@^_|~-][0-9A-Za-z!#$%&*+./:;=?@^_|~-]*'

My IGV is version 2.8.7, by the way.
Thanks for your help!

**Comment by qianxu05172019** [comment]
Thanks for your quick response! Sorry that I opened an issue in the wrong place. I saw a similar issue [#687](https://github.com/igvteam/igv.js/issues/687) . I am trying to do the same, which is uploading my transcriptome.fa as the genome and visualize my bam file.

**Comment by jrobinso** [comment]
You can load your transcriptome fasta as the reference from the "Genomes" menu ("Genomes > Load from file > your fasta").   However you are not going to be able to view that bam file in any tool because the sequence names aren't legal according to the bam specification.    That will have to be addressed first.   You might want to seek help on this in a more general forum such as SeqAnswers or Biostars.

**Comment by qianxu05172019** [comment]
OK, thanks for your help!

**Comment by jrobinso** [comment]
It would probably work to rename your sequences in the fasta file to legal BAM sequence names, then realign to the modified fasta.
