### ISSUE TITLE
Jump to read when selected by read

### ISSUE THREAD

**Issue by Rasinj** [igvteam/igv#842]
I think it would be really awesome if selecting a read by id (by right-clicking and then "Select by name") jumped directly to the location of that read.

Here's a [discussion](http://seqanswers.com/forums/showthread.php?t=51493) about the kind of workaround that is is necessary to select and view an individual read. AFAIK it is still necessary to know the start and end position of a read to find it in any case.

Here's an excerpt from that seqanswers forum discussion

>You can right click in the middle display panel. Choose "select by name" and then paste the read ID in.
> 
> You will need to combine this with Dario's solution above because even though the read is selected in IGV the display does not automatically switch to the position of the read (far as I can tell) so you would  need to manually go there yourself.

Certainly mindful that this may not be feasible/cause other issues.

Also, thanks for a great tool, it's helpful every day!

**Comment by jrobinso** [comment]
The difficulty with this is the read might not even be loaded, and if it is reads are not cached by name, this would be prohibitive from a memory point of view.    To "jump" to a selected read would potentially require reading the entire file to find it.

The "select by read name" just records the name string, so that if the read is painted it is outlined.   

The only feasible implementation would be to scan currently loaded reads searching for the read name, and if found go to that location,  but of course there is not a single location in general.  With paired reads there are at lest 2, and with split reads there can be any number.

**Comment by Rasinj** [comment]
Ah, of course, hadn't considered that.

So basically it would require some an index by read name that gives start location + end location

I guess in some hypothetical universe where that was the case, maybe for paired/split reads one may be able to step through the intervals.

Also suppose this can be closed since it's not likely there will be such an index anytime soon.

Many thanks anyways!
