### ISSUE TITLE
"Java 11 is included in the download.  " is incorrect for IGV Snapshot for Windows

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#887]
https://software.broadinstitute.org/software/igv/download_snapshot
incorrectly reports that

> IGV Snapshot for Windows
> 
> Download and run the installer.
> An IGV shortcut will be created on the Desktop; double-click it to run the application.
> Java 11 is included in the download.  

Java is **not** included. '

The workaround for me was to symlink it from the released version.

**Comment by jrobinso** [comment]
Sorry, closed inadvertently

**Comment by davideby** [comment]
Hi @malcook,

That's a typo on website; it's pointing to the "No Java" bundle instead of the "With Java" bundle.  I guess that got updated on the main Download page but not the Snapshot Download page.  You can find the installer with Java included here:
http://data.broadinstitute.org/igv/projects/downloads/snapshot/

@helgathorv, can you take a look at rewording this page somehow to make that clear?

- David

**Comment by helgathorv** [comment]
We've updated the snapshot page. It now has links to 2 windows installers - one with Java included, and one without. @malcook - thanks for letting us know.
