### ISSUE TITLE
bigBed file data is invisible/not shown in Java version, but works in the web app

### ISSUE THREAD

**Issue by therealgenna** [igvteam/igv#898]
Hi,

The bigBed file data is not seen in the Java standalone version of IGV (I've updated to IGV_2.8.13) but works fine on the web app https://igv.org/app/

I attach the screenshots and the test files (bed and bb inside zip file). I'm using Mac OSX and the bb file was created from bed file with UCSC's bedToBigBed tool.

Thank you

<img width="1679" alt="Screen Shot 2021-01-30 at 12 16 12 AM" src="https://user-images.githubusercontent.com/60659021/106348166-19a62c00-6292-11eb-91c1-be1e2a4fbbcd.png">
<img width="1147" alt="Screen Shot 2021-01-30 at 12 18 27 AM" src="https://user-images.githubusercontent.com/60659021/106348179-3c384500-6292-11eb-801c-7b10b420272f.png">
[test-bed-and-bb-files.zip](https://github.com/igvteam/igv/files/5897436/test-bed-and-bb-files.zip)

**Comment by jrobinso** [comment]
Thanks for the test data, it makes fixes much easier.   The problem was the chromosome name,  "1" in the bed and bigbed file,  "chr1" in the reference.   This should have been handled, igv.js does and so does IGV for most file types, but bigbed was the exception.   It is fixed now, and will be included in the 2.9 release which will be out this week.

**Comment by therealgenna** [comment]
Thank you very much for the quick response and the fix!
