### ISSUE TITLE
Error while viewing bw, bam coverage and junction together

### ISSUE THREAD

**Issue by hchetia** [igvteam/igv#908]
![image](https://user-images.githubusercontent.com/64626735/107432238-a86a4280-6af5-11eb-8b34-55676c1c603b.png)

![image](https://user-images.githubusercontent.com/64626735/107432352-d64f8700-6af5-11eb-9b5c-b6b3c6a90f08.png)

**Comment by jrobinso** [comment]
When reporting an issue please state the version used, and give steps to reproduce.    A title and partial screenshot is not sufficient.

**Comment by hchetia** [comment]
I am running IGV 2.8.13 on macos big sur with 8 gb mem. (my mac has 32 gb ram).

**Comment by hchetia** [comment]
SOrry but I wouldn't be able to share my track information. 

I loaded a bigwig, a bam file with junction and coverage tracks. When I try to zoom in or out, I get the error shown in the snippet above. After pressing OK and reloading the view, the tracks appear again and I am able to scroll a few kbs further till the error re-occurs.

**Comment by helgathorv** [comment]
I have not been able to reproduce this. You are not running the latest IGV - can you try the latest version from the [downloads page](http://software.broadinstitute.org/software/igv/download).

**Comment by hchetia** [comment]
Hi Helga,
I downloaded the IGV app with java for MAC OS. Can you guide on how can I run this with higher memory?

**Comment by davideby** [comment]
Hi @hchetia,

Instructions to run with higher memory are in the [readme](https://raw.githubusercontent.com/igvteam/igv/master/scripts/readme.txt) we include in our bundles, though it's a little harder to find that file in your case since you're on macOS.

The quick summary is to look for the `.igv/java_arguments` file in your user home directory.  That `.igv` directory will be hidden, so you might have to use `ls -a` in Terminal to see it.  Edit `java_arguments` with a plain-text editor like emacs or vi; I think TextEdit might work if you force it to save as plain-text.

You can change the `-Xmx8g` line to go from 8 to 16 GB.  Also be sure to remove the leading `#` character to un-comment that line.

This doesn't sound like a memory issue, but it certainly doesn't hurt to try.

- David

**Comment by hchetia** [comment]
Hi David,
Thanks for the tip. 
The issue I report here is most probably not a memory issue.
**Might I add that while scrolling through larger regions of genome (for eg >1kb), IGV track screen has 2-3 seconds of hang.**

**Comment by hchetia** [comment]
Hi David,
Is this modification applicable to the IGV app for MACOS? One weird problem that comes with this app- I am unable to see it when I do "ls" while trying to do a "chmod +x".
It seems that I cannot run this app from the command line.

**Comment by davideby** [comment]
Yeah, this modification was especially intended for the Mac App bundle (and the Windows installer, for similar reasons) because it's not really easy or recommended - and it might not even be possible for most user - to change the launcher scripts themselves due to the way they are installed.

The `.igv/java_arguments` file is meant to live **outside** the installation locations that is user-editable, in a place the launcher scripts can easily find as well.  So, just to be clear, the `.igv` directory does **not** live inside the IGV `.app` location.  You should instead be able to find it in your user home directory (that would be something like `/Users/hchetia` depending on your username on the Mac).

You should be able to run the Mac App from the command line, though that's not really it's main purpose.  You would need to `cd` to the appropriate location where you unpacked the bundle (usually Applications, but it's up to the user) and then `open ./IGV_2.9.1.app`.  There should be no need to do a `chmod +x` on this App at all.  If you are able to launch from the App's icon it's probably better to stick with that.

The readme I referenced is really more intended for command-line users, so my apologies if some of info there doesn't fit your situation.  We have a totally separate bundle meant more for the command-line but the Mac App is more appropriate for most users.

**Comment by jrobinso** [comment]
Hi all, we're off track here.   Whatever this is it is for sure not a memory issue.

**Comment by jrobinso** [comment]
@hchetia Did you try version 2.9.1 as suggested?   We will likely need some steps to reproduce to find this, if not with your files with public ones.    There might be useful information in your igv.log file, located in an "igv" folder in your home directory.  In any event the first step is to try the new release.

**Comment by hchetia** [comment]
Hi @jrobinso
As suggested, I am trying the foll. dataset with MACOS App of IGV version 2.9.1 with hg19 with the default memory.

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE33480

I also repeated using my data with the same IGV version.
No errors encountered as of now. Thanks.

**Comment by hchetia** [comment]
My session was saved in 2.8. Are there any changes needed to the session file to use it with IGV 2.9?

**Comment by jrobinso** [comment]
no
