### ISSUE TITLE
IGV 2.9.1 region of interest not aligning 

### ISSUE THREAD

**Issue by hchetia** [igvteam/igv#912]
On attempting to set regions of interest in the genome based on tracks in IGV 2.9.1 (MacOS App with Java) , the bars in track view and annotation view do not align.

![image](https://user-images.githubusercontent.com/64626735/107995251-3d64b400-6fac-11eb-9113-28fede16e15d.png)

**Comment by jrobinso** [comment]
I can't reproduce this one.    Thanks for your reports but I don't have time to guess what you did,  a standard part of a bug report are steps-to-reproduce.

**Comment by hchetia** [comment]
I have loaded 6 bam files and several annotations.

When I try to set a region of interest, as shown in the snap above, the vertical black bars (that flank the region to be saved) do not align. I anticipate that the vertical black bars and the start-ends of the Region of Interest should be same!
I don't know how I can add any further to my report. I don't see anything helpful within the igv log as well. Could you provide some guidance on how I can report the error better?

**Comment by jrobinso** [comment]
That's better, those details help, however they don't match the screenshot, and you have skipped a number of steps.  The genome assembly and chromosome (sequence) aren't specified, and it could matter because the screenshot hints at much smaller than typical sequence.  Obviously you have zoomed in at some point, before or after loading?   Also hose are wig type (maybe bigwig, maybe tdf, maybe wig,  can't tell from the screenshot.  They do not look like bam files).   In any event I can't reproduce the problem from the information provided,  but will keep an eye out for it.

<img width="1262" alt="Screen Shot 2021-02-15 at 8 22 56 PM" src="https://user-images.githubusercontent.com/933148/108018205-e8d13100-6fcb-11eb-81a7-fb6764c309fd.png">

**Comment by hchetia** [comment]
The genome assembly is hg38. The first annotation track is inbuilt with IGV.
Thanks for pointing this out. Yes, these are bigwigs.
There isn't a specific chromosome or region for this problem (but I as looking into chr 8, 9 and 10).
I had zoomed into an 18 KB window.

THE PROBLEM HAVE BEEN RESOLVED IN V2.9.2.
