### ISSUE TITLE
custom genome extremely slow to load

### ISSUE THREAD

**Issue by plijnzaad** [igvteam/igv#934]
I seem to be having an issue with custom genomes. Initially this was about a standard Hg38 human genome with 3 kb of extra constructs representing e.g. GFP, added as 5 'virtual chromosomes' each containing one virtual gene. When this did not work, I decided to just create a standard standard genome, consisting of just chr1 .. chr22, X, Y and MT, no other contigs nor virtual constructs, neither in the fasta nor the GTF. Both are properly sorted, and I did a fresh `samtools faidx ` on the fasta file. Fasta file is 3 GB, gtf is 1.1 GB. The genome was constructed using `Menu -> Genomes -> Create .genome File`, with just a fasta file and a genes files. If I unzip the resulting `.genome` file, its `property.txt` contains the following:

```
fasta=true
fastaDirectory=false
ordered=true
id=standardsimple
name=standardsimple
geneFile=simplified.gtf
sequenceLocation=../../data/refdata/extdgenome/simplified.fa
```

So far so good, but: switching genomes (i.e. to this custom genome, even though in fact it's completely standard) is _exceedingly_ slow (note this is without any bam files loaded). It takes several minutes, often giving the dreaded beachball cursor and lots of fanning. This is on a 2018 MacBook Pro (2.3 GHz, 8 GB) running OSX 10.14.6 (Mojave). I'm giving the Java process 6 GB using ` -Xmx6G` in my `~/.igv/java_arguments`,  IGV version 2.9.2 02/16/2021 1:27 PM

Is this to be expected? In the current form I can't really use IGV to quickly check the reads that are supposedly mapping to non-standard constructs.   What can I do to make a genome (especially ones with custom constructs) load faster? And what is most cricitical (apart from size) for this? indexing? sorting? compressing? length of chromosome or gene names?

I am  at a loss, would appreciate input.

**Comment by jrobinso** [comment]
Yes this would be expected, its going to take a long time to load a 1.1 GB gtf.

**Comment by jrobinso** [comment]
Annotation files that large should not be included in a ".genome" file,  I suggest tabix indexing and loading separately.

**Comment by plijnzaad** [comment]
Many thanks, that's good to know. It might be good to point this out somewhere, because based on the 'built-in' genomes it feels like you could just slap in a gtf file and expect things to work. Cheers,

Philip

**Comment by maximilianh** [comment]
Instead of making a tabix file out of a gtf, I wonder if you could reduce
the file size a lot by using a different file format, like .bed or bigBed
?

**Comment by plijnzaad** [comment]
yup, was already thinking about that. It's just that I wouldn't have
expected a large but properly sorted GTF file to be an issue. Cheers,
Ph

Op wo 17 mrt. 2021 om 10:25 schreef Maximilian Haeussler <
***@***.***>:

**Comment by maximilianh** [comment]
To convert gtf to e.g. bed you can use gtfToBed or
alternatively gtfToGenePref + genePredToBed.

**Comment by jrobinso** [comment]
@plijnzaad  I agree with @maximilianh that bed file is much more compact than the bloated gtf and gff3 formats, and this conversion will always result in better performance.   However I don't think you will reduce a 1 GB file sufficiently.   Sorting does not help without an index, and indexing within a zip (.genome) file is not possible.   I agree this should be documented.  

What I personally do when hosting a genome with annotations that large is grep out a basic feature set of interest to include by default in the .genome file,  for example the genes.   Usually the 1GB gtf/gff3 files have all annotations,  they are basically the complete database for the assembly.   

Soon there will be an alternative to the .genome file based on json in which you reference the annotation file, rather than pack it in a zip,  and the referenced file can be indexed.   The representation will be based on the igv.js "reference" object.   This actually already works but I have been too backed up to do enough testing and documentation for release.   If you would like to try it though here is an example for hg38.   This is saved as a ".json" file,  then loaded wherever you can load a .genome or fasta file.  Note in this example the gff3 annotation files are not indexed, if they were I would need to add "indexURL" properties to point to their index.

```
{
  "id": "ASM294v2",
  "name": "S. pombe (ASM294v2)",
  "fastaURL": "https://s3.amazonaws.com/igv.org.genomes/S.pombe_ASM294v2/Schizosaccharomyces_pombe_all_chromosomes.fa",
  "indexURL": "https://s3.amazonaws.com/igv.org.genomes/S.pombe_ASM294v2/Schizosaccharomyces_pombe_all_chromosomes.fa.fai",
  "tracks": [
    {
      "name": "Pombase forward strand",
      "type": "annotation",
      "format": "gff3",
      "displayMode": "EXPANDED",
      "url": "https://s3.amazonaws.com/igv.org.genomes/S.pombe_ASM294v2/Schizosaccharomyces_pombe_all_chromosomes.plus.gff3.gz",
      "indexed": false,
      "supportsWholeGenome": true,
      "labelAllFeatures": true,
      "height": 150,
      "color": "rgb(5,75,180)"
    },
    {
      "name": "Pombase reverse strand",
      "type": "annotation",
      "format": "gff3",
      "displayMode": "EXPANDED",
      "url": "https://s3.amazonaws.com/igv.org.genomes/S.pombe_ASM294v2/Schizosaccharomyces_pombe_all_chromosomes.minus.gff3.gz",
      "indexed": false,
      "supportsWholeGenome": true,
      "height": 150,
      "color": "rgb(7,123,220)"
    }
  ]
}


```

**Comment by maximilianh** [comment]
One of our formats is bigGenePred, it's actually just a bigBed file with
four additional fields for the CDS start, end and the exon frames. If you
ever are looking into more compact formats as an alternative to GFF, that
would be an option.
