### ISSUE TITLE
Crash when opening file dialog

### ISSUE THREAD

**Issue by stfacc** [igvteam/igv#958]
When I click on File -> Open, IGV crashes giving the attached log file.
I recently upgraded to Fedora 34.
Please let me know if you need more information. 

[hs_err_pid142416.log](https://github.com/igvteam/igv/files/6460353/hs_err_pid142416.log)

**Comment by helgathorv** [comment]
There is no IGV File menu item that is just "Open". 
Do you mean Open Session? Did it crash after you selected the session file?
What do you see in the IGV log in <userhome>/igv/igv.log ?

**Comment by stfacc** [comment]
File -> "Load from file", "Open session", "Save session" and "Save image", they all crash before even showing the file dialog.
"Load from server" and "Load from URI" work fine. Maybe related with the native File Dialog?

In igv.log there's only
`INFO [2021-05-12T09:13:03,662] [Main.java:205]  Startup  IGV Version 2.9.4 03/17/2021 05:06 PM
INFO [2021-05-12T09:13:03,678] [Main.java:206]  Java 11.0.10 (build 11.0.10+9) 2021-01-19
INFO [2021-05-12T09:13:03,678] [Main.java:209]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2021-05-12T09:13:03,679] [Main.java:211]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK   
INFO [2021-05-12T09:13:03,738] [Main.java:214]  Default User Directory: /home/stefano
INFO [2021-05-12T09:13:03,739] [Main.java:215]  OS: Linux 5.11.17-300.fc34.x86_64 amd64
INFO [2021-05-12T09:13:05,232] [GenomeManager.java:183]  Loading genome: /home/stefano/Documents/igv/genomes/hg19.genome
INFO [2021-05-12T09:13:11,008] [CommandListener.java:121]  Listening on port 60151
`

**Comment by jrobinso** [comment]
@stfacc Yes perhaps, I suggest you open an issue at OpenJDK however that's not going to help you now.  Sorry I don't have anything more helpful to suggest.   You might make sure your GTK libraries are up to date.

**Comment by davideby** [comment]
I know that Fedora uses Wayland, so anything relying on X11 goes through some kind of bridge adapter.  I personally don't use Wayland so I can't say much more about it.

The only really concrete suggestion that comes to mind is to try our "No Java" bundle and instead use the Java 11 supplied by the OS package manager to see if that handles things any better.  Or even a newer version of Java might work; I seem to recall someone recently reporting IGV working with Java 16 on Linux.  

One would think that a JVM vetted by the Linux distribution might have more success, and a newer version of Java might have more bug-fixes.  We only officially support Java 11, but as I said, we've had good reports from users.

If you take that route be sure not to get the "headless" JVM.  Some Linux distributions ship a default Java with no UI libraries meant for running something like Tomcat web servers since that's the main use any more.  I don't know how Fedora does things, but just make sure to use the full Java package.

- David

**Comment by stfacc** [comment]
I can confirm that everything seems to work fine using system JDK, including the native file dialogs.

From igv.log:
```
Using system JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)
WARN [2021-05-13T09:52:12,188]  [Globals.java:135] [main]  Development mode is enabled
INFO [2021-05-13T09:52:12,214]  [DirectoryManager.java:180] [main]  IGV Directory: /home/stefano/Documents/igv
INFO [2021-05-13T09:52:13,977]  [Main.java:205] [AWT-EventQueue-0]  Startup  IGV Version 2.9.4 03/17/2021 05:06 PM
INFO [2021-05-13T09:52:13,992]  [Main.java:206] [AWT-EventQueue-0]  Java 11.0.11 (build 11.0.11+9) 2021-04-20
INFO [2021-05-13T09:52:13,993]  [Main.java:209] [AWT-EventQueue-0]  Java Vendor: Red Hat, Inc. https://www.redhat.com/
INFO [2021-05-13T09:52:13,993]  [Main.java:211] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM 18.9   
INFO [2021-05-13T09:52:14,098]  [Main.java:214] [AWT-EventQueue-0]  Default User Directory: /home/stefano
INFO [2021-05-13T09:52:14,100]  [Main.java:215] [AWT-EventQueue-0]  OS: Linux 5.11.18-300.fc34.x86_64 amd64
```
