### ISSUE TITLE
htsget variants middleware

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv#983]
As discussed in https://github.com/samtools/htsjdk/issues/1555, @jrobinso will provide some wrapping class similar to the [HtsgetBAMReader](https://github.com/igvteam/igv/pull/850/files#diff-4abbb9e48d79d20e9f034b1d9e26935f3781dc30b3ca25d0402c4daa8421be44) one to [finish up the htsget PR](https://github.com/igvteam/igv/pull/850), but for Variants (VCFs and BCFs) by using Tribbles classes present in IGV.

This is meant to be a compromise solution while htsjdk gets such htsget+variants abstraction upstream ([htsjdk only provides HtsGet+BAMReader](https://github.com/samtools/htsjdk/pull/1494) is available at the time of writing this).

**Comment by jrobinso** [comment]
Note to self, example data:  https://htsget.ga4gh.org/variants/1000genomes.phase1.chrY

@brainstorm Is BCF supported on any available server?  I'm not sure how easy that will be to do, I'm going to focus on VCF.

**Comment by brainstorm** [comment]
Yes, BCF it is supported on our upcoming Rust htsget implementation: https://github.com/umccr/htsget-rs

Totally reasonable and fine to focus on VCF first though, since it'll see the most users I reckon. Thanks Jim!

**Comment by jrobinso** [comment]
@brainstorm I've added minimal support in the "htsget" branch.  You should be able to load vcf variants by URL by entering the full url, including dataset ID, in "load from URL".   For example. https://github.com/igvteam/igv/issues/983

This is very minimal, and data: URIs are not supported, consider it a prototype.   If you want to add support for data URIs or other missing features go for it.  

To determine if the server is an htsget variant source a "header" query is made,  then a test is made for the htsget container, and the format is checked (VCF only at this time).   This could be generalized for the BAM reader when it is ready.  Since this is checked after everything else fails overhead for non-htsget users is minimal.   See TrackLoader, line ~209.  Obviously this could be more elegant.
