### ISSUE TITLE
Document convention by which IGV determines which UCSC blat server to send blat requests to.

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#998]
reviewing IGV source with my read-only knowledge of java I am unable to tell how blatClient.java determines the UCSC server.

I see `String species = genome.getSpecies();`  which ultimately calls `Genome.getSpeciesForID(getUCSCId())` which in turn is document to be `A hack (obviously)`.

Can you please share what the convention being used it?

I am hosting my own copy of a genome which is supported by ucsc.  I reckon if I know this convention, I can use their blat servers.

**Comment by jrobinso** [comment]
I'm not sure what you mean by "convention", it looks like you have figured it out.   Apparently it ultimately depends on this table:  https://github.com/igvteam/igv/blob/master/src/main/resources/org/broad/igv/feature/genome/speciesMapping.txt.

The UCSC Blat support is "legacy", it needs rewritten,  the current implementation screen-scrapes the UCSC website.   Fortunately it still works for human at least.

In the meantime, because I don't know when I will get to reimplementing this if ever,  I can try updating the above table.  What genome specifically are you interested in?

**Comment by malcook** [comment]
I am currently working in zebrafish.

What I have figured out is that the value of the `id` attribute in the genome’s property.txt governs which blat database is referenced by IGV.

Knowing this allows me to craft an alternate igv genome (with different gene annotations) for zebrafish danRer11 for which I wish UCSC Blat integration to work.

Thanks

**Comment by jrobinso** [comment]
Some updated Blat documentation is available here: https://github.com/igvteam/igv/wiki/Customizing-BLAT

Currently genome ID is used to identify the Blat database, per UCSC convention, in the future it will be possible to explicitly specific a blatDB property to use instead, defaulting to the ID.  Actually this is possible now by using the not-released "json" form of a genome specification, as defined in the igv.js project.
